Repository CVEProject/cvelist, pull requests merged in 2019-07, with the labels that each got.

#2244 Ibm20190701 11220
  2019/4xxx/CVE-2019-4057.json
  2019/4xxx/CVE-2019-4101.json
  2019/4xxx/CVE-2019-4102.json
  2019/4xxx/CVE-2019-4154.json
  2019/4xxx/CVE-2019-4237.json
  2019/4xxx/CVE-2019-4295.json
  2019/4xxx/CVE-2019-4296.json
  2019/4xxx/CVE-2019-4297.json
  2019/4xxx/CVE-2019-4298.json
  2019/4xxx/CVE-2019-4299.json
  2019/4xxx/CVE-2019-4322.json
  2019/4xxx/CVE-2019-4336.json
  2019/4xxx/CVE-2019-4337.json
  2019/4xxx/CVE-2019-4357.json
  2019/4xxx/CVE-2019-4383.json
  2019/4xxx/CVE-2019-4386.json
  2019/4xxx/CVE-2019-4410.json
Labels: accepted

#2247 Ibm20190702 10596
  2019/4xxx/CVE-2019-4087.json
  2019/4xxx/CVE-2019-4088.json
  2019/4xxx/CVE-2019-4129.json
  2019/4xxx/CVE-2019-4134.json
  2019/4xxx/CVE-2019-4140.json
  2019/4xxx/CVE-2019-4260.json
  2019/4xxx/CVE-2019-4292.json
Labels: accepted

#2242 CVE-2019-10137
  2019/10xxx/CVE-2019-10137.json
Labels: accepted

#2243 CVE-2019-10136
  2019/10xxx/CVE-2019-10136.json
Labels: accepted

#2248 Upstream did not merge fix in 2.9 so it is still affected
  2019/10xxx/CVE-2019-10137.json
Labels: accepted

#2249 Upstream did not merge fix in 2.9 so it is stil laffected.
  2019/10xxx/CVE-2019-10136.json
Labels: accepted

#2250 CVE-2019-10183
  2019/10xxx/CVE-2019-10183.json
Labels: accepted

#2251 Publish 2019-3619
  2019/3xxx/CVE-2019-3619.json
Labels: accepted

#2246 CVE-2019-5630, Rapid7 issue
  2019/5xxx/CVE-2019-5630.json
Labels: needs work

#2256 Adding Cisco CVE-2019-1886
  2019/1xxx/CVE-2019-1886.json
Labels: accepted

#2255 Adding Cisco CVE-2019-1884
  2019/1xxx/CVE-2019-1884.json
Labels: accepted

#2254 Adding Cisco CVE-2019-1855
  2019/1xxx/CVE-2019-1855.json
Labels: accepted

#2258 Adding Cisco CVE-2019-1889
  2019/1xxx/CVE-2019-1889.json
Labels: accepted

#2259 Adding Cisco CVE-2019-1890
  2019/1xxx/CVE-2019-1890.json
Labels: accepted

#2253 jpcert20190704 batch.
  2019/5xxx/CVE-2019-5960.json
  2019/5xxx/CVE-2019-5961.json
  2019/5xxx/CVE-2019-5962.json
  2019/5xxx/CVE-2019-5963.json
  2019/5xxx/CVE-2019-5964.json
  2019/5xxx/CVE-2019-5965.json
  2019/5xxx/CVE-2019-5966.json
  2019/5xxx/CVE-2019-5967.json
  2019/5xxx/CVE-2019-5968.json
  2019/5xxx/CVE-2019-5969.json
  2019/5xxx/CVE-2019-5970.json
  2019/5xxx/CVE-2019-5971.json
  2019/5xxx/CVE-2019-5972.json
  2019/5xxx/CVE-2019-5973.json
  2019/5xxx/CVE-2019-5974.json
  2019/5xxx/CVE-2019-5979.json
  2019/5xxx/CVE-2019-5980.json
  2019/5xxx/CVE-2019-5981.json
  2019/5xxx/CVE-2019-5982.json
  2019/5xxx/CVE-2019-5983.json
  2019/5xxx/CVE-2019-5984.json
Labels: accepted

#2262 Adding Cisco CVE-2019-1892
  2019/1xxx/CVE-2019-1892.json
Labels: accepted

#2261 Adding Cisco CVE-2019-1891
  2019/1xxx/CVE-2019-1891.json
Labels: accepted

#2260 Adding Cisco CVE-2019-1887
  2019/1xxx/CVE-2019-1887.json
Labels: accepted

#2266 Adding Cisco CVE-2019-1911
  2019/1xxx/CVE-2019-1911.json
Labels: accepted

#2265 Adding Cisco CVE-2019-1909
  2019/1xxx/CVE-2019-1909.json
Labels: accepted

#2264 Adding Cisco CVE-2019-1894
  2019/1xxx/CVE-2019-1894.json
Labels: accepted

#2263 Adding Cisco CVE-2019-1893
  2019/1xxx/CVE-2019-1893.json
Labels: accepted

#2268 Adding Cisco CVE-2019-1922
  2019/1xxx/CVE-2019-1922.json
Labels: accepted

#2267 Adding Cisco CVE-2019-1921
  2019/1xxx/CVE-2019-1921.json
Labels: accepted

#2272 Adding Cisco CVE-2019-1933
  2019/1xxx/CVE-2019-1933.json
Labels: accepted

#2271 Adding Cisco CVE-2019-1932
  2019/1xxx/CVE-2019-1932.json
Labels: accepted

#2270 Adding Cisco CVE-2019-1931
  2019/1xxx/CVE-2019-1931.json
Labels: accepted

#2269 Adding Cisco CVE-2019-1930
  2019/1xxx/CVE-2019-1930.json
Labels: accepted

#2281 Adding Cisco CVE-2019-1873
  2019/1xxx/CVE-2019-1873.json
Labels: accepted

#2286 Add CVEs for Jenkins 2019-07-11 security advisory
  2019/10xxx/CVE-2019-10340.json
  2019/10xxx/CVE-2019-10341.json
  2019/10xxx/CVE-2019-10342.json
  2019/10xxx/CVE-2019-10346.json
  2019/10xxx/CVE-2019-10347.json
  2019/10xxx/CVE-2019-10348.json
  2019/10xxx/CVE-2019-10349.json
  2019/10xxx/CVE-2019-10350.json
  2019/10xxx/CVE-2019-10351.json
Labels: accepted

#2235 add CVE-2019-11268
  2019/11xxx/CVE-2019-11268.json
Labels: accepted

#2252 Adding SensePost reference with vulnerability details
  2017/11xxx/CVE-2017-11774.json
Labels: accepted

#2273 Adding TWCERT/CC CVE-2019-9886 and CVE-2019-11062
  2019/11xxx/CVE-2019-11062.json
  2019/9xxx/CVE-2019-9886.json
Labels: accepted

#2274 init CVE-2019-10135
  2019/10xxx/CVE-2019-10135.json
Labels: accepted

#2275 init CVE-2019-3889
  2019/3xxx/CVE-2019-3889.json
Labels: accepted

#2276 Cve 2019 10193
  2019/10xxx/CVE-2019-10192.json
  2019/10xxx/CVE-2019-10193.json
Labels: accepted

#2277 init CVE-2019-10194
  2019/10xxx/CVE-2019-10194.json
Labels: accepted

#2279 Initial CVE-2019-7003 Publication
  2019/7xxx/CVE-2019-7003.json
Labels: accepted

#2282 CVE assignments in Juniper July 2019 advisory bundle.
  2019/0xxx/CVE-2019-0046.json
  2019/0xxx/CVE-2019-0048.json
  2019/0xxx/CVE-2019-0049.json
  2019/0xxx/CVE-2019-0052.json
  2019/0xxx/CVE-2019-0053.json
Labels: accepted

#2287 Ibm20190711 155025
  2018/1xxx/CVE-2018-1968.json
  2019/4xxx/CVE-2019-4118.json
  2019/4xxx/CVE-2019-4131.json
  2019/4xxx/CVE-2019-4193.json
  2019/4xxx/CVE-2019-4263.json
Labels: accepted

#2285 CVE updates for Siemens AD-2019-07
  2018/13xxx/CVE-2018-13808.json
  2018/13xxx/CVE-2018-13809.json
  2018/13xxx/CVE-2018-13810.json
  2019/10xxx/CVE-2019-10915.json
  2019/10xxx/CVE-2019-10916.json
  2019/10xxx/CVE-2019-10917.json
  2019/10xxx/CVE-2019-10918.json
  2019/10xxx/CVE-2019-10930.json
  2019/10xxx/CVE-2019-10931.json
  2019/10xxx/CVE-2019-10933.json
  2019/10xxx/CVE-2019-10935.json
  2019/6xxx/CVE-2019-6568.json
  2019/6xxx/CVE-2019-6575.json
Labels: accepted

#2288 CVE-2019-5629 content
  2019/5xxx/CVE-2019-5629.json
Labels: accepted

#2289 init CVE-2019-10190
  2019/10xxx/CVE-2019-10190.json
Labels: question

#2293 Update CVE-2019-6160.json
  2019/6xxx/CVE-2019-6160.json
Labels: accepted

#2294 Publish CVE-2019-3571
  2019/3xxx/CVE-2019-3571.json
Labels: accepted

#2296 Ibm20190717 95814
  2018/1xxx/CVE-2018-1921.json
  2018/2xxx/CVE-2018-2021.json
  2018/2xxx/CVE-2018-2022.json
  2019/4xxx/CVE-2019-4054.json
  2019/4xxx/CVE-2019-4194.json
  2019/4xxx/CVE-2019-4211.json
  2019/4xxx/CVE-2019-4430.json
Labels: accepted

#2297 CVEs for 2019-07-17 Jenkins security advisory
  2019/10xxx/CVE-2019-10352.json
  2019/10xxx/CVE-2019-10353.json
  2019/10xxx/CVE-2019-10354.json
Labels: accepted

#2300 Adding Cisco CVE-2019-1917
  2019/1xxx/CVE-2019-1917.json
Labels: accepted

#2298 Two CVEs for Eclipse OpenJ9
  2019/11xxx/CVE-2019-11771.json
  2019/11xxx/CVE-2019-11772.json
Labels: accepted

#2302 Adding Cisco CVE-2019-1920
  2019/1xxx/CVE-2019-1920.json
Labels: accepted

#2301 Adding Cisco CVE-2019-1919
  2019/1xxx/CVE-2019-1919.json
Labels: accepted

#2306 Adding Cisco CVE-2019-1942
  2019/1xxx/CVE-2019-1942.json
Labels: accepted

#2305 Adding Cisco CVE-2019-1941
  2019/1xxx/CVE-2019-1941.json
Labels: accepted

#2304 Adding Cisco CVE-2019-1940
  2019/1xxx/CVE-2019-1940.json
Labels: accepted

#2303 Adding Cisco CVE-2019-1923
  2019/1xxx/CVE-2019-1923.json
Labels: accepted

#2307 Adding Cisco CVE-2019-1943
  2019/1xxx/CVE-2019-1943.json
Labels: accepted

#2299 Publish CVE-2019-3570
  2019/3xxx/CVE-2019-3570.json
Labels: accepted

#2292 Added CVE-3734, 3741, 3794
  2019/3xxx/CVE-2019-3734.json
  2019/3xxx/CVE-2019-3741.json
  2019/3xxx/CVE-2019-3794.json
Labels: accepted

#2308 Publish 2019 - 3592
  2019/3xxx/CVE-2019-3592.json
Labels: accepted

#2309 July 2019 Out of Band
  2019/1xxx/CVE-2019-1068.json
  2019/1xxx/CVE-2019-1082.json
  2019/1xxx/CVE-2019-1167.json
Labels: accepted

#2311 Ibm20190722 9297
  2018/2xxx/CVE-2018-2024.json
  2019/4xxx/CVE-2019-4236.json
  2019/4xxx/CVE-2019-4267.json
Labels: accepted

#2310 Qualcomm_7-22-2019
  2018/13xxx/CVE-2018-13896.json
  2018/13xxx/CVE-2018-13924.json
  2018/13xxx/CVE-2018-13927.json
  2019/2xxx/CVE-2019-2243.json
  2019/2xxx/CVE-2019-2260.json
  2019/2xxx/CVE-2019-2261.json
  2019/2xxx/CVE-2019-2264.json
  2019/2xxx/CVE-2019-2269.json
  2019/2xxx/CVE-2019-2277.json
  2019/2xxx/CVE-2019-2279.json
  2019/2xxx/CVE-2019-2287.json
  2019/2xxx/CVE-2019-2292.json
Labels: accepted

#2312 CVE-2019-10173
  2019/10xxx/CVE-2019-10173.json
Labels: accepted

#2314 Publish 2019-3595
  2019/3xxx/CVE-2019-3595.json
Labels: accepted

#2315 Publish 2019-3591
  2019/3xxx/CVE-2019-3591.json
Labels: accepted

#2316 Update CVE-2019-3622.json
  2019/3xxx/CVE-2019-3622.json
Labels: accepted

#2320 Ibm20190725 102511
  2019/4xxx/CVE-2019-4116.json
  2019/4xxx/CVE-2019-4212.json
  2019/4xxx/CVE-2019-4415.json
  2019/4xxx/CVE-2019-4439.json
Labels: accepted

#2317 Submit CVE-2019-3621
  2019/3xxx/CVE-2019-3621.json
Labels: accepted

#2318 Adding TWCERT/CC CVE-2019-9884 and CVE-2019-9885
  2019/9xxx/CVE-2019-9884.json
  2019/9xxx/CVE-2019-9885.json
Labels: accepted

#2319 Qualcomm_7-25-2019
  2018/13xxx/CVE-2018-13897.json
  2019/2xxx/CVE-2019-2235.json
  2019/2xxx/CVE-2019-2236.json
  2019/2xxx/CVE-2019-2237.json
  2019/2xxx/CVE-2019-2238.json
  2019/2xxx/CVE-2019-2239.json
  2019/2xxx/CVE-2019-2240.json
  2019/2xxx/CVE-2019-2241.json
  2019/2xxx/CVE-2019-2253.json
  2019/2xxx/CVE-2019-2254.json
  2019/2xxx/CVE-2019-2263.json
  2019/2xxx/CVE-2019-2272.json
  2019/2xxx/CVE-2019-2273.json
  2019/2xxx/CVE-2019-2276.json
  2019/2xxx/CVE-2019-2278.json
  2019/2xxx/CVE-2019-2281.json
  2019/2xxx/CVE-2019-2290.json
  2019/2xxx/CVE-2019-2293.json
  2019/2xxx/CVE-2019-2298.json
  2019/2xxx/CVE-2019-2299.json
  2019/2xxx/CVE-2019-2301.json
  2019/2xxx/CVE-2019-2305.json
  2019/2xxx/CVE-2019-2306.json
  2019/2xxx/CVE-2019-2307.json
  2019/2xxx/CVE-2019-2308.json
  2019/2xxx/CVE-2019-2309.json
  2019/2xxx/CVE-2019-2312.json
  2019/2xxx/CVE-2019-2314.json
  2019/2xxx/CVE-2019-2316.json
  2019/2xxx/CVE-2019-2322.json
  2019/2xxx/CVE-2019-2326.json
  2019/2xxx/CVE-2019-2327.json
  2019/2xxx/CVE-2019-2328.json
  2019/2xxx/CVE-2019-2330.json
  2019/2xxx/CVE-2019-2334.json
  2019/2xxx/CVE-2019-2343.json
  2019/2xxx/CVE-2019-2345.json
  2019/2xxx/CVE-2019-2346.json
Labels: accepted

#2321 Publish CVE-2019-11922
  2019/11xxx/CVE-2019-11922.json
Labels: accepted

#2322 CVE-2019-10184
  2019/10xxx/CVE-2019-10184.json
Labels: accepted

#2323 Publish CVE-2019-11921
  2019/11xxx/CVE-2019-11921.json
Labels: accepted

#2324 JPCERT/CC 2019-07-26
  2019/6xxx/CVE-2019-6002.json
Labels: accepted

#2204 Added CVE-2019-1105
  2019/1xxx/CVE-2019-1105.json
Labels: needs-work

#2332 Ibm20190730 9233
  2019/4xxx/CVE-2019-4062.json
  2019/4xxx/CVE-2019-4285.json
  2019/4xxx/CVE-2019-4456.json
Labels: accepted

#2325 CVE-2019-11775
  2019/11xxx/CVE-2019-11775.json
Labels: accepted

#2327 init CVE-2019-10130
  2019/10xxx/CVE-2019-10130.json
Labels: accepted

#2328 init CVE-2019-10138
  2019/10xxx/CVE-2019-10138.json
Labels: accepted

#2329 init CVE-2018-16871
  2018/16xxx/CVE-2018-16871.json
Labels: accepted

#2330 init CVE-2019-10141
  2019/10xxx/CVE-2019-10141.json
Labels: accepted

#2331 init CVE-2019-10142
  2019/10xxx/CVE-2019-10142.json
Labels: accepted

#2333 Update of OpenSSL's CVE-2019-1552
  2019/1xxx/CVE-2019-1552.json
Labels: accepted

#2334 Elastic 2019-07-30 release
  2019/7xxx/CVE-2019-7610.json
  2019/7xxx/CVE-2019-7614.json
  2019/7xxx/CVE-2019-7615.json
  2019/7xxx/CVE-2019-7616.json
Labels: accepted

#2335 CVE-2019-10152
  2019/10xxx/CVE-2019-10152.json
Labels: accepted

#2336 CVE-2019-10153
  2019/10xxx/CVE-2019-10153.json
Labels: accepted

#2337 CVE-2019-10156
  2019/10xxx/CVE-2019-10156.json
Labels: accepted

#2338 CVE-2019-10161
  2019/10xxx/CVE-2019-10161.json
Labels: accepted

#2339 CVE-2019-10162
  2019/10xxx/CVE-2019-10162.json
Labels: accepted

#2340 CVE-2019-10163
  2019/10xxx/CVE-2019-10163.json
Labels: accepted

#2341 CVE-2019-10165
  2019/10xxx/CVE-2019-10165.json
Labels: accepted

#2342 Add 2019-07-31 Jenkins security advisory
  2019/10xxx/CVE-2019-10343.json
  2019/10xxx/CVE-2019-10344.json
  2019/10xxx/CVE-2019-10345.json
  2019/10xxx/CVE-2019-10355.json
  2019/10xxx/CVE-2019-10356.json
  2019/10xxx/CVE-2019-10357.json
  2019/10xxx/CVE-2019-10358.json
  2019/10xxx/CVE-2019-10359.json
  2019/10xxx/CVE-2019-10360.json
  2019/10xxx/CVE-2019-10361.json
  2019/10xxx/CVE-2019-10362.json
  2019/10xxx/CVE-2019-10363.json
  2019/10xxx/CVE-2019-10364.json
  2019/10xxx/CVE-2019-10365.json
  2019/10xxx/CVE-2019-10366.json
Labels: accepted

#2343 init CVE-2018-16860
  2018/16xxx/CVE-2018-16860.json
Labels: accepted

#2344 Ibm20190731 121914
  2019/4xxx/CVE-2019-4163.json
  2019/4xxx/CVE-2019-4165.json
Labels: accepted

#2345 Adding Cisco CVE-2019-1901
  2019/1xxx/CVE-2019-1901.json
Labels: accepted

#2347 CVE-2019-10189
  2019/10xxx/CVE-2019-10189.json
Labels: accepted

#2348 CVE-2019-10188
  2019/10xxx/CVE-2019-10188.json
Labels: accepted

#2349 CVE-2019-10187
  2019/10xxx/CVE-2019-10187.json
Labels: accepted

#2352 CVE-2019-10198
  2019/10xxx/CVE-2019-10198.json
Labels: accepted

#2351 Initial CVE-2019-7000 Publication
  2019/7xxx/CVE-2019-7000.json
Labels: accepted

#2350 CVE-2019-10186
  2019/10xxx/CVE-2019-10186.json
Labels: accepted

#2346 CVE-2019-10182
  2019/10xxx/CVE-2019-10182.json
Labels: accepted

#2354 CVE-2019-10185
  2019/10xxx/CVE-2019-10185.json
Labels: accepted

#2356 CVE-2019-10181
  2019/10xxx/CVE-2019-10181.json
Labels: accepted

#2359 CVE-2015-5297
  2015/5xxx/CVE-2015-5297.json
Labels: accepted
