Repository CVEProject/cvelist, pull requests merged in 2019-10, with the labels that each got.

#2605 Add CVEs for 2019-10-01 security advisory
  2019/10xxx/CVE-2019-10431.json
  2019/10xxx/CVE-2019-10432.json
  2019/10xxx/CVE-2019-10433.json
  2019/10xxx/CVE-2019-10434.json
  2019/10xxx/CVE-2019-10435.json
Labels: accepted

#2601 Publish CVE-2019-11275
  2019/11xxx/CVE-2019-11275.json
Labels: accepted

#2604 CVE-2019-10202 init
  2019/10xxx/CVE-2019-10202.json
Labels: accepted

#2606 Ibm20191001 102611
  2019/4xxx/CVE-2019-4246.json
  2019/4xxx/CVE-2019-4494.json
  2019/4xxx/CVE-2019-4495.json
  2019/4xxx/CVE-2019-4497.json
Labels: accepted

#2607 Elastic 2019-10-01 security advisory
  2019/7xxx/CVE-2019-7618.json
Labels: accepted

#2608 update references and description for CVE-2019-16760
  2019/16xxx/CVE-2019-16760.json
Labels: accepted

#2595 CVE-2019-0231 update
  2019/0xxx/CVE-2019-0231.json
Labels: needs work

#2594 Updates for Online Store System v1.0 multiple vulnerabilities
  2019/8xxx/CVE-2019-8288.json
  2019/8xxx/CVE-2019-8289.json
  2019/8xxx/CVE-2019-8290.json
  2019/8xxx/CVE-2019-8291.json
  2019/8xxx/CVE-2019-8292.json
Labels: accepted

#2609 Ibm20191002 104125
  2019/4xxx/CVE-2019-4520.json
  2019/4xxx/CVE-2019-4538.json
  2019/4xxx/CVE-2019-4539.json
  2019/4xxx/CVE-2019-4542.json
  2019/4xxx/CVE-2019-4549.json
Labels: accepted

#2610 Adding Cisco CVE-2019-12630
  2019/12xxx/CVE-2019-12630.json
Labels: accepted

#2611 Adding Cisco CVE-2019-12631
  2019/12xxx/CVE-2019-12631.json
Labels: accepted

#2603 CVE-2019-10212 init
  2019/10xxx/CVE-2019-10212.json
Labels: accepted

#2614 Adding Cisco CVE-2019-12673
  2019/12xxx/CVE-2019-12673.json
Labels: accepted

#2612 Publish CVE-2019-11929
  2019/11xxx/CVE-2019-11929.json
Labels: accepted

#2616 CVE-2019-3834 init
  2019/3xxx/CVE-2019-3834.json
Labels: accepted

#2617 Ibm20191003 10045
  2019/4xxx/CVE-2019-4422.json
  2019/4xxx/CVE-2019-4441.json
Labels: accepted

#2618 Publish CVE-2019-11932
  2019/11xxx/CVE-2019-11932.json
Labels: accepted

#2619 ZDI Assigns the following FoxIt CVEs:
  2019/13xxx/CVE-2019-13323.json
  2019/13xxx/CVE-2019-13324.json
  2019/13xxx/CVE-2019-13325.json
Labels: accepted

#2620 ZDI assigns the following Foxit CVEs:
  2019/13xxx/CVE-2019-13326.json
  2019/13xxx/CVE-2019-13327.json
  2019/13xxx/CVE-2019-13328.json
  2019/13xxx/CVE-2019-13329.json
  2019/13xxx/CVE-2019-13330.json
  2019/13xxx/CVE-2019-13331.json
  2019/13xxx/CVE-2019-13332.json
Labels: accepted

#2623 Ibm20191004 10315
  2019/4xxx/CVE-2019-4227.json
  2019/4xxx/CVE-2019-4514.json
  2019/4xxx/CVE-2019-4564.json
Labels: accepted

#2622 JPCERT/CC CVE-2019-6015
  2019/6xxx/CVE-2019-6015.json
Labels: accepted

#2552 Information for CVE-2019-3688
  2019/3xxx/CVE-2019-3688.json
Labels: accepted

#2624 Added CVE-2019-3745
  2019/3xxx/CVE-2019-3745.json
Labels: accepted

#2625 CVE-2019-14845
  2019/14xxx/CVE-2019-14845.json
Labels: accepted

#2626 CVE-2019-14846
  2019/14xxx/CVE-2019-14846.json
Labels: accepted

#2627 CVE-2019-10215
  2019/10xxx/CVE-2019-10215.json
Labels: accepted

#2628 TIBCO MDM XSS vulnerability
  2019/11xxx/CVE-2019-11212.json
Labels: accepted

#2629 [ISC] update vuln info for 9 CVEs from 2018 & 2019, processing backlog
  2018/5xxx/CVE-2018-5732.json
  2018/5xxx/CVE-2018-5743.json
  2018/5xxx/CVE-2018-5744.json
  2018/5xxx/CVE-2018-5745.json
  2019/6xxx/CVE-2019-6465.json
  2019/6xxx/CVE-2019-6467.json
  2019/6xxx/CVE-2019-6468.json
  2019/6xxx/CVE-2019-6469.json
  2019/6xxx/CVE-2019-6471.json
Labels: accepted

#2630 Publish CVE-2019-3652
  2019/3xxx/CVE-2019-3652.json
Labels: accepted

#2632 Ibm20191009 105523
  2019/4xxx/CVE-2019-4512.json
  2019/4xxx/CVE-2019-4558.json
Labels: accepted

#2633 VU#763073, public at 10am Oct 9 2019
  2019/9xxx/CVE-2019-9535.json
Labels: accepted

#2634 Added CVE-2019-3765
  2019/3xxx/CVE-2019-3765.json
Labels: accepted

#2635 juniper-2019-10-09 CVE publications
  2019/0xxx/CVE-2019-0047.json
  2019/0xxx/CVE-2019-0050.json
  2019/0xxx/CVE-2019-0051.json
  2019/0xxx/CVE-2019-0054.json
  2019/0xxx/CVE-2019-0055.json
  2019/0xxx/CVE-2019-0056.json
  2019/0xxx/CVE-2019-0057.json
  2019/0xxx/CVE-2019-0058.json
  2019/0xxx/CVE-2019-0059.json
  2019/0xxx/CVE-2019-0060.json
  2019/0xxx/CVE-2019-0061.json
  2019/0xxx/CVE-2019-0062.json
  2019/0xxx/CVE-2019-0063.json
  2019/0xxx/CVE-2019-0064.json
  2019/0xxx/CVE-2019-0065.json
  2019/0xxx/CVE-2019-0066.json
  2019/0xxx/CVE-2019-0067.json
  2019/0xxx/CVE-2019-0068.json
  2019/0xxx/CVE-2019-0069.json
  2019/0xxx/CVE-2019-0070.json
  2019/0xxx/CVE-2019-0071.json
  2019/0xxx/CVE-2019-0072.json
  2019/0xxx/CVE-2019-0073.json
  2019/0xxx/CVE-2019-0074.json
  2019/0xxx/CVE-2019-0075.json
Labels: accepted

#2636 October 2019 Patch Tuesday
  2019/0xxx/CVE-2019-0608.json
  2019/1xxx/CVE-2019-1060.json
  2019/1xxx/CVE-2019-1070.json
  2019/1xxx/CVE-2019-1166.json
  2019/1xxx/CVE-2019-1230.json
  2019/1xxx/CVE-2019-1238.json
  2019/1xxx/CVE-2019-1239.json
  2019/1xxx/CVE-2019-1307.json
  2019/1xxx/CVE-2019-1308.json
  2019/1xxx/CVE-2019-1311.json
  2019/1xxx/CVE-2019-1313.json
  2019/1xxx/CVE-2019-1314.json
  2019/1xxx/CVE-2019-1315.json
  2019/1xxx/CVE-2019-1316.json
  2019/1xxx/CVE-2019-1317.json
  2019/1xxx/CVE-2019-1318.json
  2019/1xxx/CVE-2019-1319.json
  2019/1xxx/CVE-2019-1320.json
  2019/1xxx/CVE-2019-1321.json
  2019/1xxx/CVE-2019-1322.json
  2019/1xxx/CVE-2019-1323.json
  2019/1xxx/CVE-2019-1325.json
  2019/1xxx/CVE-2019-1326.json
  2019/1xxx/CVE-2019-1327.json
  2019/1xxx/CVE-2019-1328.json
  2019/1xxx/CVE-2019-1329.json
  2019/1xxx/CVE-2019-1330.json
  2019/1xxx/CVE-2019-1331.json
  2019/1xxx/CVE-2019-1333.json
  2019/1xxx/CVE-2019-1334.json
  2019/1xxx/CVE-2019-1335.json
  2019/1xxx/CVE-2019-1336.json
  2019/1xxx/CVE-2019-1337.json
  2019/1xxx/CVE-2019-1338.json
  2019/1xxx/CVE-2019-1339.json
  2019/1xxx/CVE-2019-1340.json
  2019/1xxx/CVE-2019-1341.json
  2019/1xxx/CVE-2019-1342.json
  2019/1xxx/CVE-2019-1343.json
  2019/1xxx/CVE-2019-1344.json
  2019/1xxx/CVE-2019-1345.json
  2019/1xxx/CVE-2019-1346.json
  2019/1xxx/CVE-2019-1347.json
  2019/1xxx/CVE-2019-1356.json
  2019/1xxx/CVE-2019-1357.json
  2019/1xxx/CVE-2019-1358.json
  2019/1xxx/CVE-2019-1359.json
  2019/1xxx/CVE-2019-1361.json
  2019/1xxx/CVE-2019-1362.json
  2019/1xxx/CVE-2019-1363.json
  2019/1xxx/CVE-2019-1364.json
  2019/1xxx/CVE-2019-1365.json
  2019/1xxx/CVE-2019-1366.json
  2019/1xxx/CVE-2019-1368.json
  2019/1xxx/CVE-2019-1369.json
  2019/1xxx/CVE-2019-1371.json
  2019/1xxx/CVE-2019-1372.json
  2019/1xxx/CVE-2019-1375.json
  2019/1xxx/CVE-2019-1376.json
  2019/1xxx/CVE-2019-1378.json
Labels: accepted

#2637 CVE updates for Siemens-AD-2019-10
  2018/4xxx/CVE-2018-4843.json
  2019/10xxx/CVE-2019-10916.json
  2019/10xxx/CVE-2019-10917.json
  2019/10xxx/CVE-2019-10918.json
  2019/10xxx/CVE-2019-10923.json
  2019/10xxx/CVE-2019-10935.json
  2019/10xxx/CVE-2019-10936.json
  2019/13xxx/CVE-2019-13921.json
  2019/13xxx/CVE-2019-13929.json
  2019/6xxx/CVE-2019-6568.json
Labels: accepted

#2638 Ibm20191010 95619
  2019/4xxx/CVE-2019-4265.json
Labels: accepted

#2639 VU#719689
  2019/9xxx/CVE-2019-9529.json
  2019/9xxx/CVE-2019-9530.json
  2019/9xxx/CVE-2019-9531.json
  2019/9xxx/CVE-2019-9532.json
  2019/9xxx/CVE-2019-9533.json
  2019/9xxx/CVE-2019-9534.json
Labels: accepted

#2642 Ibm20191014 95134
  2019/4xxx/CVE-2019-4572.json
Labels: accepted

#2643 Added CVE-2019-3767
  2019/3xxx/CVE-2019-3767.json
Labels: accepted

#2646 CVE-2019-14832
  2019/14xxx/CVE-2019-14832.json
Labels: accepted

#2645 CVE-2019-14820
  2019/14xxx/CVE-2019-14820.json
Labels: accepted

#2648 Correction on CWE and description of CVE-2019-3738
  2019/3xxx/CVE-2019-3738.json
Labels: accepted

#2652 Ibm20191016 84327
  2019/4xxx/CVE-2019-4031.json
Labels: accepted

#2653 Add CVEs for Jenkins 2019-10-16 security advisory
  2019/10xxx/CVE-2019-10436.json
  2019/10xxx/CVE-2019-10437.json
  2019/10xxx/CVE-2019-10438.json
  2019/10xxx/CVE-2019-10439.json
  2019/10xxx/CVE-2019-10440.json
  2019/10xxx/CVE-2019-10441.json
  2019/10xxx/CVE-2019-10442.json
  2019/10xxx/CVE-2019-10443.json
  2019/10xxx/CVE-2019-10444.json
  2019/10xxx/CVE-2019-10445.json
  2019/10xxx/CVE-2019-10446.json
  2019/10xxx/CVE-2019-10447.json
  2019/10xxx/CVE-2019-10448.json
  2019/10xxx/CVE-2019-10449.json
  2019/10xxx/CVE-2019-10450.json
  2019/10xxx/CVE-2019-10451.json
  2019/10xxx/CVE-2019-10452.json
  2019/10xxx/CVE-2019-10453.json
  2019/10xxx/CVE-2019-10454.json
  2019/10xxx/CVE-2019-10455.json
  2019/10xxx/CVE-2019-10456.json
  2019/10xxx/CVE-2019-10457.json
  2019/10xxx/CVE-2019-10458.json
Labels: accepted

#2651 Add CVE-2019-11281
  2019/11xxx/CVE-2019-11281.json
Labels: accepted

#2650 [ISC] Update information for 3 Kea CVEs from August 2019
  2019/6xxx/CVE-2019-6472.json
  2019/6xxx/CVE-2019-6473.json
  2019/6xxx/CVE-2019-6474.json
Labels: accepted

#2654 Kubernetes updates
  2019/11xxx/CVE-2019-11253.json
Labels: needs-work

#2656 CVE-2019-17631
  2019/17xxx/CVE-2019-17631.json
Labels: accepted

#2660 Add TWCERT/CC CVE-2019-13411
  2019/13xxx/CVE-2019-13411.json
Labels: accepted

#2659 Trend Micro CVE-2019-15626 and CVE-2019-15627 submission
  2019/15xxx/CVE-2019-15626.json
  2019/15xxx/CVE-2019-15627.json
Labels: accepted

#2657 [ISC] 2 BIND9 Vulns made public
  2019/6xxx/CVE-2019-6475.json
  2019/6xxx/CVE-2019-6476.json
Labels: accepted

#2661 Add TWCERT/CC CVE-2019-15064
  2019/15xxx/CVE-2019-15064.json
Labels: accepted

#2662 Add TWCERT/CC CVE-2019-13412
  2019/13xxx/CVE-2019-13412.json
Labels: accepted

#2663 Add TWCERT/CC CVE-2019-15066
  2019/15xxx/CVE-2019-15066.json
Labels: accepted

#2664 Add TWCERT/CC CVE-2019-15065
  2019/15xxx/CVE-2019-15065.json
Labels: accepted

#2665 Add TWCERT/CC CVE-2019-13409
  2019/13xxx/CVE-2019-13409.json
Labels: accepted

#2666 Add TWCERT/CC CVE-2019-13410
  2019/13xxx/CVE-2019-13410.json
Labels: accepted

#2667 CVE-2019-10215 init
  2019/10xxx/CVE-2019-10215.json
Labels: accepted

#2670 Trend Micro publish CVE-2019-9491
  2019/9xxx/CVE-2019-9491.json
Labels: accepted

#2671 Ibm20191022 102158
  2019/4xxx/CVE-2019-4523.json
Labels: accepted

#2675 Add CVEs for 2019-10-23 Jenkins security advisory
  2019/10xxx/CVE-2019-10459.json
  2019/10xxx/CVE-2019-10460.json
  2019/10xxx/CVE-2019-10461.json
  2019/10xxx/CVE-2019-10462.json
  2019/10xxx/CVE-2019-10463.json
  2019/10xxx/CVE-2019-10464.json
  2019/10xxx/CVE-2019-10465.json
  2019/10xxx/CVE-2019-10466.json
  2019/10xxx/CVE-2019-10467.json
  2019/10xxx/CVE-2019-10468.json
  2019/10xxx/CVE-2019-10469.json
  2019/10xxx/CVE-2019-10470.json
  2019/10xxx/CVE-2019-10471.json
  2019/10xxx/CVE-2019-10472.json
  2019/10xxx/CVE-2019-10473.json
  2019/10xxx/CVE-2019-10474.json
  2019/10xxx/CVE-2019-10475.json
  2019/10xxx/CVE-2019-10476.json
Labels: accepted

#2673 Add CVE-2019-11283
  2019/11xxx/CVE-2019-11283.json
Labels: accepted

#2676 Ibm20191024 75625
  2019/4xxx/CVE-2019-4397.json
  2019/4xxx/CVE-2019-4398.json
  2019/4xxx/CVE-2019-4459.json
  2019/4xxx/CVE-2019-4486.json
Labels: accepted

#2677 Ibm20191025 122815
  2019/4xxx/CVE-2019-4036.json
  2019/4xxx/CVE-2019-4394.json
  2019/4xxx/CVE-2019-4395.json
  2019/4xxx/CVE-2019-4396.json
  2019/4xxx/CVE-2019-4399.json
  2019/4xxx/CVE-2019-4400.json
  2019/4xxx/CVE-2019-4461.json
Labels: accepted

#2678 ZDI assigns the following Foxit CVEs
  2019/17xxx/CVE-2019-17138.json
  2019/17xxx/CVE-2019-17139.json
  2019/17xxx/CVE-2019-17140.json
  2019/17xxx/CVE-2019-17141.json
  2019/17xxx/CVE-2019-17142.json
  2019/17xxx/CVE-2019-17143.json
  2019/17xxx/CVE-2019-17144.json
  2019/17xxx/CVE-2019-17145.json
Labels: accepted

#2679 Report CVE-2019-11043
  2019/11xxx/CVE-2019-11043.json
Labels: accepted

#2680 Publish CVE-2019-3636
  2019/3xxx/CVE-2019-3636.json
Labels: accepted

#2681 Trend Micro CVE-2019-18187, 18188, 18189 submissions
  2019/18xxx/CVE-2019-18187.json
  2019/18xxx/CVE-2019-18188.json
  2019/18xxx/CVE-2019-18189.json
Labels: accepted

#2682 Ibm20191028 193230
  2019/4xxx/CVE-2019-4306.json
  2019/4xxx/CVE-2019-4307.json
  2019/4xxx/CVE-2019-4309.json
  2019/4xxx/CVE-2019-4311.json
  2019/4xxx/CVE-2019-4314.json
  2019/4xxx/CVE-2019-4329.json
  2019/4xxx/CVE-2019-4330.json
  2019/4xxx/CVE-2019-4339.json
  2019/4xxx/CVE-2019-4546.json
  2019/4xxx/CVE-2019-4600.json
Labels: accepted

#2683 init CVE-2019-10209
  2019/10xxx/CVE-2019-10209.json
Labels: accepted

#2684 CVE-2019-10210 init
  2019/10xxx/CVE-2019-10210.json
Labels: accepted

#2686 CVE-2019-10208 init
  2019/10xxx/CVE-2019-10208.json
Labels: accepted

#2685 CVE-2019-10211 init
  2019/10xxx/CVE-2019-10211.json
Labels: accepted

#2687 Add Elastic IDs
  2019/7xxx/CVE-2019-7619.json
  2019/7xxx/CVE-2019-7620.json
Labels: accepted

#2689 Cna/isc/2019102101
  2018/5xxx/CVE-2018-5735.json
  2018/5xxx/CVE-2018-5742.json
Labels: accepted
