Repository CVEProject/cvelist, pull requests merged in 2019-03, with the labels that each got.

#1645 Supportutils
  2018/19xxx/CVE-2018-19636.json
  2018/19xxx/CVE-2018-19637.json
  2018/19xxx/CVE-2018-19638.json
  2018/19xxx/CVE-2018-19639.json
  2018/19xxx/CVE-2018-19640.json
Labels: JSON Valid

#1650 Ibm20190305 115557
  2018/1xxx/CVE-2018-1875.json
  2018/1xxx/CVE-2018-1899.json
  2018/1xxx/CVE-2018-1937.json
  2018/1xxx/CVE-2018-1938.json
  2018/1xxx/CVE-2018-1939.json
  2019/4xxx/CVE-2019-4027.json
  2019/4xxx/CVE-2019-4028.json
  2019/4xxx/CVE-2019-4029.json
  2019/4xxx/CVE-2019-4032.json
  2019/4xxx/CVE-2019-4063.json
Labels: JSON Valid, Ownership Validated, accepted

#1646 CVE-2019-3824
  2019/3xxx/CVE-2019-3824.json
Labels: JSON Valid, Ownership Validated, accepted

#1663 Ibm20190306 143633
  2018/1xxx/CVE-2018-1911.json
  2018/1xxx/CVE-2018-1912.json
  2019/4xxx/CVE-2019-4030.json
Labels: JSON Valid, Ownership Validated, accepted

#1651 Add OpenSSL CVE-2019-1543
  2019/1xxx/CVE-2019-1543.json
Labels: JSON Valid, Ownership Validated, accepted

#1652 Adding Cisco CVE-2019-1585
  2019/1xxx/CVE-2019-1585.json
Labels: JSON Valid, Ownership Validated, accepted

#1653 Adding Cisco CVE-2019-1588
  2019/1xxx/CVE-2019-1588.json
Labels: JSON Valid, Ownership Validated, accepted

#1654 Adding Cisco CVE-2019-1591
  2019/1xxx/CVE-2019-1591.json
Labels: JSON Valid, Ownership Validated, accepted

#1655 Adding Cisco CVE-2019-1593
  2019/1xxx/CVE-2019-1593.json
Labels: JSON Valid, Ownership Validated, accepted

#1656 Adding Cisco CVE-2019-1594
  2019/1xxx/CVE-2019-1594.json
Labels: JSON Valid, Ownership Validated, accepted

#1657 Adding Cisco CVE-2019-1595
  2019/1xxx/CVE-2019-1595.json
Labels: JSON Valid, Ownership Validated, accepted

#1658 Adding Cisco CVE-2019-1596
  2019/1xxx/CVE-2019-1596.json
Labels: JSON Valid, Ownership Validated, accepted

#1659 Adding Cisco CVE-2019-1597
  2019/1xxx/CVE-2019-1597.json
Labels: JSON Valid, Ownership Validated, accepted

#1660 Adding Cisco CVE-2019-1598
  2019/1xxx/CVE-2019-1598.json
Labels: JSON Valid, Ownership Validated, accepted

#1661 Adding Cisco CVE-2019-1599
  2019/1xxx/CVE-2019-1599.json
Labels: JSON Valid, Ownership Validated, accepted

#1662 Adding Cisco CVE-2019-1600
  2019/1xxx/CVE-2019-1600.json
Labels: JSON Valid, Ownership Validated, accepted

#1664 TIBCO Jaspersoft suite vulnerabilities.
  2018/18xxx/CVE-2018-18808.json
  2018/18xxx/CVE-2018-18809.json
  2018/18xxx/CVE-2018-18815.json
  2018/18xxx/CVE-2018-18816.json
  2019/8xxx/CVE-2019-8986.json
Labels: JSON Valid, Ownership Validated, accepted

#1606 Publish CVE-2019-3779,3780
  2019/3xxx/CVE-2019-3779.json
  2019/3xxx/CVE-2019-3780.json
Labels: JSON Valid, Ownership Validated, accepted

#1666 Add CVE-2018-20234 CVE-2018-20235 CVE-2018-20236
  2018/20xxx/CVE-2018-20234.json
  2018/20xxx/CVE-2018-20235.json
  2018/20xxx/CVE-2018-20236.json
Labels: JSON Valid, Ownership Validated, accepted

#1667 Adding Cisco CVE-2019-1601
  2019/1xxx/CVE-2019-1601.json
Labels: JSON Valid, Ownership Validated, accepted

#1668 Adding Cisco CVE-2019-1602
  2019/1xxx/CVE-2019-1602.json
Labels: JSON Valid, Ownership Validated, accepted

#1669 Adding Cisco CVE-2019-1603
  2019/1xxx/CVE-2019-1603.json
Labels: JSON Valid, Ownership Validated, accepted

#1670 Adding Cisco CVE-2019-1604
  2019/1xxx/CVE-2019-1604.json
Labels: JSON Valid, Ownership Validated, accepted

#1671 Adding Cisco CVE-2019-1605
  2019/1xxx/CVE-2019-1605.json
Labels: JSON Valid, Ownership Validated, accepted

#1672 Adding Cisco CVE-2019-1606
  2019/1xxx/CVE-2019-1606.json
Labels: JSON Valid, Ownership Validated, accepted

#1673 Adding Cisco CVE-2019-1607
  2019/1xxx/CVE-2019-1607.json
Labels: JSON Valid, Ownership Validated, accepted

#1674 Adding Cisco CVE-2019-1608
  2019/1xxx/CVE-2019-1608.json
Labels: JSON Valid, Ownership Validated, accepted

#1675 Adding Cisco CVE-2019-1609
  2019/1xxx/CVE-2019-1609.json
Labels: JSON Valid, Ownership Validated, accepted

#1676 Adding Cisco CVE-2019-1610
  2019/1xxx/CVE-2019-1610.json
Labels: JSON Valid, Ownership Validated, accepted

#1677 Adding Cisco CVE-2019-1611
  2019/1xxx/CVE-2019-1611.json
Labels: JSON Valid, Ownership Validated, accepted

#1678 Adding Cisco CVE-2019-1612
  2019/1xxx/CVE-2019-1612.json
Labels: JSON Valid, Ownership Validated, accepted

#1679 Adding Cisco CVE-2019-1613
  2019/1xxx/CVE-2019-1613.json
Labels: JSON Valid, Ownership Validated, accepted

#1680 Adding Cisco CVE-2019-1614
  2019/1xxx/CVE-2019-1614.json
Labels: JSON Valid, Ownership Validated, accepted

#1681 Adding Cisco CVE-2019-1615
  2019/1xxx/CVE-2019-1615.json
Labels: JSON Valid, Ownership Validated, accepted

#1683 Adding Cisco CVE-2019-1616
  2019/1xxx/CVE-2019-1616.json
Labels: JSON Valid, Ownership Validated, accepted

#1684 Adding Cisco CVE-2019-1617
  2019/1xxx/CVE-2019-1617.json
Labels: JSON Valid, Ownership Validated, accepted

#1685 Adding Cisco CVE-2019-1618
  2019/1xxx/CVE-2019-1618.json
Labels: JSON Valid, Ownership Validated, accepted

#1686 Adding Cisco CVE-2019-1690
  2019/1xxx/CVE-2019-1690.json
Labels: JSON Valid, Ownership Validated, accepted

#1687 Adding Cisco CVE-2019-1702
  2019/1xxx/CVE-2019-1702.json
Labels: JSON Valid, Ownership Validated, accepted

#1688 Adding Cisco CVE-2019-1707
  2019/1xxx/CVE-2019-1707.json
Labels: JSON Valid, Ownership Validated, accepted

#1682 Ibm20190311 144529
  2018/1xxx/CVE-2018-1890.json
  2018/1xxx/CVE-2018-1902.json
  2018/1xxx/CVE-2018-1911.json
  2018/1xxx/CVE-2018-1912.json
  2018/1xxx/CVE-2018-1922.json
  2018/1xxx/CVE-2018-1923.json
  2018/1xxx/CVE-2018-1974.json
  2018/1xxx/CVE-2018-1978.json
  2018/1xxx/CVE-2018-1980.json
  2018/1xxx/CVE-2018-1998.json
  2018/2xxx/CVE-2018-2009.json
  2019/4xxx/CVE-2019-4015.json
  2019/4xxx/CVE-2019-4016.json
  2019/4xxx/CVE-2019-4030.json
Labels: JSON Valid, Ownership Validated, accepted

#1689 JPCERT 2019-03-12 batch
  2019/5xxx/CVE-2019-5917.json
  2019/5xxx/CVE-2019-5918.json
  2019/5xxx/CVE-2019-5919.json
  2019/5xxx/CVE-2019-5920.json
  2019/5xxx/CVE-2019-5921.json
  2019/5xxx/CVE-2019-5922.json
  2019/5xxx/CVE-2019-5923.json
  2019/5xxx/CVE-2019-5924.json
  2019/5xxx/CVE-2019-5925.json
Labels: JSON Valid, Ownership Validated

#1690 Publish CVE-2019-3615
  2019/3xxx/CVE-2019-3615.json
Labels: JSON Valid, Ownership Validated, accepted

#1695 Adding Cisco CVE-2018-0389
  2019/0xxx/CVE-2018-0389.json
Labels: JSON Valid, Ownership Validated, accepted

#1696 Adding Cisco CVE-2019-1723
  2019/1xxx/CVE-2019-1723.json
Labels: JSON Valid, Ownership Validated, accepted

#1697 Publish CVE-2019-3711,3715,3716,3785
  2019/3xxx/CVE-2019-3711.json
  2019/3xxx/CVE-2019-3715.json
  2019/3xxx/CVE-2019-3716.json
  2019/3xxx/CVE-2019-3785.json
Labels: JSON Valid, Ownership Validated, accepted

#1692 CVE-2019-3816
  2019/3xxx/CVE-2019-3816.json
Labels: JSON Valid, Ownership Validated, accepted

#1693 CVE-2019-3833
  2019/3xxx/CVE-2019-3833.json
Labels: JSON Valid, Ownership Validated, accepted

#1700 Ibm20190314 102130
  2018/1xxx/CVE-2018-1908.json
  2018/1xxx/CVE-2018-1910.json
  2018/1xxx/CVE-2018-1914.json
  2018/1xxx/CVE-2018-1916.json
  2018/1xxx/CVE-2018-1929.json
  2018/1xxx/CVE-2018-1952.json
  2018/1xxx/CVE-2018-1982.json
  2018/1xxx/CVE-2018-1983.json
  2018/1xxx/CVE-2018-1984.json
  2019/4xxx/CVE-2019-4034.json
Labels: accepted

#1691 Add 2019-5616, Circuitwerkes Sicon-8 RO vuln
  2019/5xxx/CVE-2019-5616.json
Labels: JSON Valid, Ownership Validated, accepted

#1701 Update CVE-2019-6149.json
  2019/6xxx/CVE-2019-6149.json
Labels: JSON Valid, Ownership Validated, accepted

#1716 Ibm20190319 94314
  2018/1xxx/CVE-2018-1836.json
  2019/4xxx/CVE-2019-4094.json
Labels: accepted

#1702 Withdrawing CVEs from 2018
  2018/0xxx/CVE-2018-0143.json
  2018/0xxx/CVE-2018-0153.json
  2018/0xxx/CVE-2018-0191.json
  2018/0xxx/CVE-2018-0236.json
  2018/0xxx/CVE-2018-0246.json
  2018/0xxx/CVE-2018-0265.json
Labels: JSON Valid, Ownership Validated, accepted, staged

#1703 Ibm20190315 133420
  2018/17xxx/CVE-2018-17482.json
  2018/17xxx/CVE-2018-17483.json
  2018/17xxx/CVE-2018-17484.json
  2018/17xxx/CVE-2018-17485.json
  2018/17xxx/CVE-2018-17486.json
  2018/17xxx/CVE-2018-17487.json
  2018/17xxx/CVE-2018-17488.json
  2018/17xxx/CVE-2018-17489.json
  2018/17xxx/CVE-2018-17490.json
  2018/17xxx/CVE-2018-17491.json
  2018/17xxx/CVE-2018-17492.json
  2018/17xxx/CVE-2018-17493.json
  2018/17xxx/CVE-2018-17494.json
  2018/17xxx/CVE-2018-17495.json
  2018/17xxx/CVE-2018-17496.json
  2018/17xxx/CVE-2018-17497.json
  2018/17xxx/CVE-2018-17499.json
  2018/17xxx/CVE-2018-17500.json
  2018/17xxx/CVE-2018-17502.json
Labels: accepted, staged

#1704 CVE-2019-3832
  2019/3xxx/CVE-2019-3832.json
Labels: accepted

#1714 CVE-2017-2659
  2017/2xxx/CVE-2017-2659.json
Labels: accepted

#1717 CVE-2019-3859
  2019/3xxx/CVE-2019-3859.json
Labels: accepted

#1718 CVE-2019-3862
  2019/3xxx/CVE-2019-3862.json
Labels: accepted

#1739 Ibm20190321 10333
  2017/1xxx/CVE-2017-1713.json
  2018/1xxx/CVE-2018-1992.json
Labels: accepted

#1720 CVE-2019-3858
  2019/3xxx/CVE-2019-3858.json
Labels: accepted

#1721 CVE-2019-3871
  2019/3xxx/CVE-2019-3871.json
Labels: accepted

#1747 Ibm20190322 114650
  2019/4xxx/CVE-2019-4035.json
  2019/4xxx/CVE-2019-4052.json
Labels: accepted

#1734 Adding Cisco CVE-2019-1766
  2019/1xxx/CVE-2019-1766.json
Labels: accepted

#1733 Adding Cisco CVE-2019-1765
  2019/1xxx/CVE-2019-1765.json
Labels: accepted

#1732 Adding Cisco CVE-2019-1764
  2019/1xxx/CVE-2019-1764.json
Labels: accepted

#1731 Adding Cisco CVE-2019-1763
  2019/1xxx/CVE-2019-1763.json
Labels: accepted

#1730 Adding Cisco CVE-2019-1716
  2019/1xxx/CVE-2019-1716.json
Labels: accepted

#1707 Cve 2019 3808
  2019/3xxx/CVE-2019-3808.json
Labels: accepted

#1710 CVE-2018-16838
  2018/16xxx/CVE-2018-16838.json
Labels: accepted

#1711 CVE-2018-16858
  2018/16xxx/CVE-2018-16858.json
Labels: accepted

#1713 CVE-2019-3827
  2019/3xxx/CVE-2019-3827.json
Labels: accepted

#1715 CVE-2017-7510
  2017/7xxx/CVE-2017-7510.json
Labels: accepted

#1722 CVE-2019-3863
  2019/3xxx/CVE-2019-3863.json
Labels: accepted

#1749 Ibm20190325 14858
  2019/4xxx/CVE-2019-4046.json
Labels: accepted

#1750 CVE-2019-3879
  2019/3xxx/CVE-2019-3879.json
Labels: accepted

#1743 CVE-2019-3838
  2019/3xxx/CVE-2019-3838.json
Labels: accepted

#1742 CVE-2019-3835
  2019/3xxx/CVE-2019-3835.json
Labels: accepted

#1728 CVE-2019-3874
  2019/3xxx/CVE-2019-3874.json
Labels: accepted

#1726 CVE-2019-3861
  2019/3xxx/CVE-2019-3861.json
Labels: accepted

#1725 CVE-2019-3860
  2019/3xxx/CVE-2019-3860.json
Labels: accepted

#1724 CVE-2019-3857
  2019/3xxx/CVE-2019-3857.json
Labels: accepted

#1723 CVE-2019-3856
  2019/3xxx/CVE-2019-3856.json
Labels: accepted

#1729 Update Elastic CVE IDs
  2019/7xxx/CVE-2019-7608.json
  2019/7xxx/CVE-2019-7609.json
  2019/7xxx/CVE-2019-7610.json
  2019/7xxx/CVE-2019-7611.json
  2019/7xxx/CVE-2019-7612.json
  2019/7xxx/CVE-2019-7613.json
Labels: accepted

#1735 Add CVE-2019-3395 CVE-2019-3396
  2019/3xxx/CVE-2019-3395.json
  2019/3xxx/CVE-2019-3396.json
Labels: accepted

#1746 Update CVE-2018-6703
  2018/6xxx/CVE-2018-6703.json
Labels: accepted

#1737 Publish 2019-3597
  2019/3xxx/CVE-2019-3597.json
Labels: accepted

#1738 Publish 2019-3606
  2019/3xxx/CVE-2019-3606.json
Labels: accepted

#1740 CVE-2019-3878
  2019/3xxx/CVE-2019-3878.json
Labels: accepted

#1744 rejected
  2017/2xxx/CVE-2017-2660.json
Labels: accepted

#1752 CVE-2018-16856
  2018/16xxx/CVE-2018-16856.json
Labels: accepted

#1753 CVE-2019-3804
  2019/3xxx/CVE-2019-3804.json
Labels: accepted

#1761 CVE-2019-3848
  2019/3xxx/CVE-2019-3848.json
Labels: accepted

#1762 CVE-2019-3849
  2019/3xxx/CVE-2019-3849.json
Labels: accepted

#1763 CVE-2019-3850
  2019/3xxx/CVE-2019-3850.json
Labels: accepted

#1764 CVE-2019-3851
  2019/3xxx/CVE-2019-3851.json
Labels: accepted

#1765 CVE-2019-3852
  2019/3xxx/CVE-2019-3852.json
Labels: accepted

#1756 CVE-2019-3826
  2019/3xxx/CVE-2019-3826.json
Labels: accepted

#1760 Multiple vulnerabilities in TIBCO Spotfire Data Science product family.
  2019/8xxx/CVE-2019-8987.json
  2019/8xxx/CVE-2019-8988.json
  2019/8xxx/CVE-2019-8989.json
Labels: accepted

#1706 CVE-2019-3830
  2019/3xxx/CVE-2019-3830.json
Labels: accepted

#1745 CVE-2019-3877
  2019/3xxx/CVE-2019-3877.json
Labels: accepted

#1751 CVE-2018-10934
  2018/10xxx/CVE-2018-10934.json
Labels: accepted

#1754 CVE-2019-3814
  2019/3xxx/CVE-2019-3814.json
Labels: accepted

#1755 CVE-2019-3821
  2019/3xxx/CVE-2019-3821.json
Labels: accepted

#1757 CVE-2019-3828
  2019/3xxx/CVE-2019-3828.json
Labels: accepted

#1758 CVE-2019-3840
  2019/3xxx/CVE-2019-3840.json
Labels: accepted

#1759 CVE-2019-3847
  2019/3xxx/CVE-2019-3847.json
Labels: accepted

#1712 CVE-2019-3817
  2019/3xxx/CVE-2019-3817.json
Labels: accepted

#1767 jpcert20190327 batch.
  2018/16xxx/CVE-2018-16207.json
  2019/5xxx/CVE-2019-5926.json
  2019/5xxx/CVE-2019-5927.json
Labels: accepted

#1768 CVE-2019-3829
  2019/3xxx/CVE-2019-3829.json
Labels: accepted

#1769 Eclipse Mosquitto CVEs
  2018/12xxx/CVE-2018-12546.json
  2018/12xxx/CVE-2018-12550.json
  2018/12xxx/CVE-2018-12551.json
Labels: accepted

#1770 CVE-2017-7655
  2017/7xxx/CVE-2017-7655.json
Labels: accepted

#1771 CVE-2018-12545
  2018/12xxx/CVE-2018-12545.json
Labels: accepted

#1776 Adding Cisco CVE-2019-1737
  2019/1xxx/CVE-2019-1737.json
Labels: accepted

#1777 Adding Cisco CVE-2019-1738
  2019/1xxx/CVE-2019-1738.json
Labels: accepted

#1778 Adding Cisco CVE-2019-1739
  2019/1xxx/CVE-2019-1739.json
Labels: accepted

#1780 Adding Cisco CVE-2019-1741
  2019/1xxx/CVE-2019-1741.json
Labels: accepted

#1779 Adding Cisco CVE-2019-1740
  2019/1xxx/CVE-2019-1740.json
Labels: accepted

#1782 Adding Cisco CVE-2019-1743
  2019/1xxx/CVE-2019-1743.json
Labels: accepted

#1781 Adding Cisco CVE-2019-1742
  2019/1xxx/CVE-2019-1742.json
Labels: accepted

#1783 Adding Cisco CVE-2019-1745
  2019/1xxx/CVE-2019-1745.json
Labels: accepted

#1784 Adding Cisco CVE-2019-1746
  2019/1xxx/CVE-2019-1746.json
Labels: accepted

#1786 Adding Cisco CVE-2019-1748
  2019/1xxx/CVE-2019-1748.json
Labels: accepted

#1785 Adding Cisco CVE-2019-1747
  2019/1xxx/CVE-2019-1747.json
Labels: accepted

#1788 Adding Cisco CVE-2019-1750
  2019/1xxx/CVE-2019-1750.json
Labels: accepted

#1787 Adding Cisco CVE-2019-1749
  2019/1xxx/CVE-2019-1749.json
Labels: accepted

#1789 Adding Cisco CVE-2019-1751
  2019/1xxx/CVE-2019-1751.json
Labels: accepted

#1790 Adding Cisco CVE-2019-1752
  2019/1xxx/CVE-2019-1752.json
Labels: accepted

#1791 Adding Cisco CVE-2019-1753
  2019/1xxx/CVE-2019-1753.json
Labels: accepted

#1794 Adding Cisco CVE-2019-1756
  2019/1xxx/CVE-2019-1756.json
Labels: accepted

#1793 Adding Cisco CVE-2019-1755
  2019/1xxx/CVE-2019-1755.json
Labels: accepted

#1792 Adding Cisco CVE-2019-1754
  2019/1xxx/CVE-2019-1754.json
Labels: accepted

#1796 Adding Cisco CVE-2019-1758
  2019/1xxx/CVE-2019-1758.json
Labels: accepted

#1795 Adding Cisco CVE-2019-1757
  2019/1xxx/CVE-2019-1757.json
Labels: accepted

#1799 Adding Cisco CVE-2019-1761
  2019/1xxx/CVE-2019-1761.json
Labels: accepted

#1798 Adding Cisco CVE-2019-1760
  2019/1xxx/CVE-2019-1760.json
Labels: accepted

#1797 Adding Cisco CVE-2019-1759
  2019/1xxx/CVE-2019-1759.json
Labels: accepted

#1800 Adding Cisco CVE-2019-1762
  2019/1xxx/CVE-2019-1762.json
Labels: accepted

#1772 CVE-2019-3869
  2019/3xxx/CVE-2019-3869.json
Labels: accepted

#1801 Add CVE-2017-18105 CVE-2017-18106 CVE-2017-18107 CVE-2017-18108 CVE-2017-18109 CVE-2017-18110 CVE-2017-18111
  2017/18xxx/CVE-2017-18105.json
  2017/18xxx/CVE-2017-18106.json
  2017/18xxx/CVE-2017-18108.json
  2017/18xxx/CVE-2017-18109.json
  2017/18xxx/CVE-2017-18110.json
  2017/18xxx/CVE-2017-18111.json
Labels: accepted
