Repository CVEProject/cvelist, pull requests merged in 2020-06, with the labels that each got.

#3928 Add CVE-2020-4013 CVE-2020-4014 CVE-2020-4015 CVE-2020-4016 CVE-2020-4017 CVE-2020-4018 CVE-2020-4019 CVE-2020-4020 CVE-2020-4021 CVE-2020-4023
  2020/4xxx/CVE-2020-4013.json
  2020/4xxx/CVE-2020-4014.json
  2020/4xxx/CVE-2020-4015.json
  2020/4xxx/CVE-2020-4016.json
  2020/4xxx/CVE-2020-4017.json
  2020/4xxx/CVE-2020-4018.json
  2020/4xxx/CVE-2020-4019.json
  2020/4xxx/CVE-2020-4020.json
  2020/4xxx/CVE-2020-4021.json
  2020/4xxx/CVE-2020-4023.json
Labels: accepted

#3932 VU#636397 IP-in-IP
  2020/10xxx/CVE-2020-10136.json
Labels: accepted

#3826 Added CVE-2020-10739
  2020/10xxx/CVE-2020-10739.json
Labels: needs work

#3934 Ibm20200602 9393
  2020/4xxx/CVE-2020-4360.json
  2020/4xxx/CVE-2020-4366.json
  2020/4xxx/CVE-2020-4367.json
  2020/4xxx/CVE-2020-4431.json
  2020/4xxx/CVE-2020-4503.json
Labels: accepted

#3936 Add CVE-2020-5410
  2020/5xxx/CVE-2020-5410.json
Labels: accepted

#3938 Add CVE-2020-4026
  2020/4xxx/CVE-2020-4026.json
Labels: accepted

#3940 Add CVEs for 2020-06-03 Jenkins security advisory
  2020/2xxx/CVE-2020-2190.json
  2020/2xxx/CVE-2020-2191.json
  2020/2xxx/CVE-2020-2192.json
  2020/2xxx/CVE-2020-2193.json
  2020/2xxx/CVE-2020-2194.json
  2020/2xxx/CVE-2020-2195.json
  2020/2xxx/CVE-2020-2196.json
  2020/2xxx/CVE-2020-2197.json
  2020/2xxx/CVE-2020-2198.json
  2020/2xxx/CVE-2020-2199.json
  2020/2xxx/CVE-2020-2200.json
Labels: accepted

#3941 Ibm20200603 102645
  2020/4xxx/CVE-2020-4177.json
  2020/4xxx/CVE-2020-4180.json
  2020/4xxx/CVE-2020-4182.json
  2020/4xxx/CVE-2020-4187.json
  2020/4xxx/CVE-2020-4190.json
  2020/4xxx/CVE-2020-4307.json
Labels: accepted

#3942 add CVE-2020-4035 for GHSA-38f9-m297-6q9g
  2020/4xxx/CVE-2020-4035.json
Labels: accepted

#3944 Adding Cisco CVE-2020-3319
  2020/3xxx/CVE-2020-3319.json
Labels: accepted

#3943 Adding Cisco CVE-2020-3321
  2020/3xxx/CVE-2020-3321.json
Labels: accepted

#3945 Adding Cisco CVE-2020-3322
  2020/3xxx/CVE-2020-3322.json
Labels: accepted

#3990 Adding Cisco CVE-2020-3201
  2020/3xxx/CVE-2020-3201.json
Labels: accepted

#3989 Adding Cisco CVE-2020-3203
  2020/3xxx/CVE-2020-3203.json
Labels: accepted

#3988 Adding Cisco CVE-2020-3204
  2020/3xxx/CVE-2020-3204.json
Labels: accepted

#3987 Adding Cisco CVE-2020-3205
  2020/3xxx/CVE-2020-3205.json
Labels: accepted

#3986 Adding Cisco CVE-2020-3206
  2020/3xxx/CVE-2020-3206.json
Labels: accepted

#3985 Adding Cisco CVE-2020-3207
  2020/3xxx/CVE-2020-3207.json
Labels: accepted

#3984 Adding Cisco CVE-2020-3208
  2020/3xxx/CVE-2020-3208.json
Labels: accepted

#3983 Adding Cisco CVE-2020-3209
  2020/3xxx/CVE-2020-3209.json
Labels: accepted

#3982 Adding Cisco CVE-2020-3210
  2020/3xxx/CVE-2020-3210.json
Labels: accepted

#3979 Adding Cisco CVE-2020-3213
  2020/3xxx/CVE-2020-3213.json
Labels: accepted

#3977 Adding Cisco CVE-2020-3215
  2020/3xxx/CVE-2020-3215.json
Labels: accepted

#3976 Adding Cisco CVE-2020-3216
  2020/3xxx/CVE-2020-3216.json
Labels: accepted

#3975 Adding Cisco CVE-2020-3217
  2020/3xxx/CVE-2020-3217.json
Labels: accepted

#3973 Adding Cisco CVE-2020-3219
  2020/3xxx/CVE-2020-3219.json
Labels: accepted

#3972 Adding Cisco CVE-2020-3220
  2020/3xxx/CVE-2020-3220.json
Labels: accepted

#3970 Adding Cisco CVE-2020-3222
  2020/3xxx/CVE-2020-3222.json
Labels: accepted

#3969 Adding Cisco CVE-2020-3223
  2020/3xxx/CVE-2020-3223.json
Labels: accepted

#3968 Adding Cisco CVE-2020-3224
  2020/3xxx/CVE-2020-3224.json
Labels: accepted

#3967 Adding Cisco CVE-2020-3225
  2020/3xxx/CVE-2020-3225.json
Labels: accepted

#3966 Adding Cisco CVE-2020-3226
  2020/3xxx/CVE-2020-3226.json
Labels: accepted

#3965 Adding Cisco CVE-2020-3227
  2020/3xxx/CVE-2020-3227.json
Labels: accepted

#3964 Adding Cisco CVE-2020-3229
  2020/3xxx/CVE-2020-3229.json
Labels: accepted

#3963 Adding Cisco CVE-2020-3230
  2020/3xxx/CVE-2020-3230.json
Labels: accepted

#3962 Adding Cisco CVE-2020-3231
  2020/3xxx/CVE-2020-3231.json
Labels: accepted

#3961 Adding Cisco CVE-2020-3228
  2020/3xxx/CVE-2020-3228.json
Labels: accepted

#3993 Adding Cisco CVE-2020-3198
  2020/3xxx/CVE-2020-3198.json
Labels: accepted

#3992 Adding Cisco CVE-2020-3199
  2020/3xxx/CVE-2020-3199.json
Labels: accepted

#3991 Adding Cisco CVE-2020-3200
  2020/3xxx/CVE-2020-3200.json
Labels: accepted

#3960 Adding Cisco CVE-2020-3232
  2020/3xxx/CVE-2020-3232.json
Labels: accepted

#3958 Add Elastic CVE IDs
  2020/7xxx/CVE-2020-7010.json
  2020/7xxx/CVE-2020-7011.json
  2020/7xxx/CVE-2020-7012.json
  2020/7xxx/CVE-2020-7013.json
  2020/7xxx/CVE-2020-7014.json
  2020/7xxx/CVE-2020-7015.json
Labels: accepted

#3956 Adding Cisco CVE-2020-3235
  2020/3xxx/CVE-2020-3235.json
Labels: accepted

#3955 Adding Cisco CVE-2020-3237
  2020/3xxx/CVE-2020-3237.json
Labels: accepted

#3954 Adding Cisco CVE-2020-3238
  2020/3xxx/CVE-2020-3238.json
Labels: accepted

#3953 Adding Cisco CVE-2020-3257
  2020/3xxx/CVE-2020-3257.json
Labels: accepted

#3952 Adding Cisco CVE-2020-3258
  2020/3xxx/CVE-2020-3258.json
Labels: accepted

#3951 Adding Cisco CVE-2020-3267
  2020/3xxx/CVE-2020-3267.json
Labels: accepted

#3950 Adding Cisco CVE-2020-3281
  2020/3xxx/CVE-2020-3281.json
Labels: accepted

#3948 Adding Cisco CVE-2020-3335
  2020/3xxx/CVE-2020-3335.json
Labels: accepted

#3947 Adding Cisco CVE-2020-3339
  2020/3xxx/CVE-2020-3339.json
Labels: accepted

#3946 Adding Cisco CVE-2020-3353
  2020/3xxx/CVE-2020-3353.json
Labels: accepted

#3994 add CVE-2020-5295 for GHSA-r23f-c2j5-rx2f
  2020/5xxx/CVE-2020-5295.json
Labels: accepted

#3997 add CVE-2020-5298 for GHSA-gg6x-xx78-448c
  2020/5xxx/CVE-2020-5298.json
Labels: accepted

#3996 add CVE-2020-5297 for GHSA-9722-rr68-rfpg
  2020/5xxx/CVE-2020-5297.json
Labels: accepted

#3995 add CVE-2020-5296 for GHSA-jv6v-fvvx-4932
  2020/5xxx/CVE-2020-5296.json
Labels: accepted

#3998 add CVE-2020-5299 for GHSA-4rhm-m2fp-hx7q
  2020/5xxx/CVE-2020-5299.json
Labels: accepted

#3999 add CVE-2020-11080 for GHSA-q5wr-xfw9-q7xr
  2020/11xxx/CVE-2020-11080.json
Labels: accepted

#4000 Chrome CVEs. Recent and a few historical.
  2011/1xxx/CVE-2011-1805.json
  2011/2xxx/CVE-2011-2863.json
  2020/6xxx/CVE-2020-6419.json
  2020/6xxx/CVE-2020-6453.json
  2020/6xxx/CVE-2020-6493.json
  2020/6xxx/CVE-2020-6494.json
  2020/6xxx/CVE-2020-6495.json
  2020/6xxx/CVE-2020-6496.json
  2020/6xxx/CVE-2020-6497.json
  2020/6xxx/CVE-2020-6498.json
  2020/6xxx/CVE-2020-6499.json
  2020/6xxx/CVE-2020-6500.json
  2020/6xxx/CVE-2020-6501.json
  2020/6xxx/CVE-2020-6502.json
  2020/6xxx/CVE-2020-6503.json
  2020/6xxx/CVE-2020-6504.json
Labels: accepted

#4001 add CVE-2020-11091 for GHSA-59qg-grp7-5r73
  2020/11xxx/CVE-2020-11091.json
Labels: accepted

#4002 add CVE-2020-11094 for GHSA-c8wh-6jw4-2h79
  2020/11xxx/CVE-2020-11094.json
Labels: accepted

#4003 Avaya ASA 2020 077 publication for CVE-2020-7030
  2020/7xxx/CVE-2020-7030.json
Labels: accepted

#4004 Ibm20200604 93058
  2020/4xxx/CVE-2020-4183.json
  2020/4xxx/CVE-2020-4191.json
  2020/4xxx/CVE-2020-4193.json
  2020/4xxx/CVE-2020-4509.json
Labels: accepted

#4005 Publish details for CVE-2020-8555
  2020/8xxx/CVE-2020-8555.json
Labels: accepted

#4006 JPCERT/CC CVE-2020-5591
  2020/5xxx/CVE-2020-5591.json
Labels: accepted

#4007 Added information for CVE-2020-8103
  2020/8xxx/CVE-2020-8103.json
Labels: accepted

#4008 Ibm20200605 85241
  2020/4xxx/CVE-2020-4229.json
  2020/4xxx/CVE-2020-4448.json
  2020/4xxx/CVE-2020-4449.json
  2020/4xxx/CVE-2020-4450.json
Labels: accepted

#3897 Update 2020 05 26
  2020/10xxx/CVE-2020-10019.json
  2020/10xxx/CVE-2020-10021.json
  2020/10xxx/CVE-2020-10022.json
  2020/10xxx/CVE-2020-10023.json
  2020/10xxx/CVE-2020-10024.json
  2020/10xxx/CVE-2020-10027.json
  2020/10xxx/CVE-2020-10028.json
  2020/10xxx/CVE-2020-10058.json
  2020/10xxx/CVE-2020-10059.json
  2020/10xxx/CVE-2020-10060.json
  2020/10xxx/CVE-2020-10061.json
  2020/10xxx/CVE-2020-10062.json
  2020/10xxx/CVE-2020-10063.json
  2020/10xxx/CVE-2020-10067.json
  2020/10xxx/CVE-2020-10068.json
  2020/10xxx/CVE-2020-10070.json
  2020/10xxx/CVE-2020-10071.json
Labels: needs-work

#4010 Add TWCERT/CC CVE-2020-12773
  2020/12xxx/CVE-2020-12773.json
Labels: accepted

#4012 Ibm20200608 85339
  2020/4xxx/CVE-2020-4529.json
Labels: accepted

#4013 add CVE-2020-4038 for GHSA-4852-vrh7-28rf
  2020/4xxx/CVE-2020-4038.json
Labels: accepted

#4014 add CVE-2020-4040 GHSA-2q66-6cc3-6xm8
  2020/4xxx/CVE-2020-4040.json
Labels: accepted

#4015 add CVE-2020-4041 for GHSA-68q3-7wjp-7q3j
  2020/4xxx/CVE-2020-4041.json
Labels: accepted

#4016 JPCERT/CC 20200609 CVE-2020-5589 added.
  2020/5xxx/CVE-2020-5589.json
Labels: accepted

#4018 TIBCO-2020-014: CVE-2020-9411 & CVE-2020-9412
  2020/9xxx/CVE-2020-9411.json
  2020/9xxx/CVE-2020-9412.json
Labels: accepted

#4020 June Advisories
  2019/6xxx/CVE-2019-6173.json
  2019/6xxx/CVE-2019-6196.json
  2020/8xxx/CVE-2020-8320.json
  2020/8xxx/CVE-2020-8321.json
  2020/8xxx/CVE-2020-8322.json
  2020/8xxx/CVE-2020-8323.json
  2020/8xxx/CVE-2020-8331.json
  2020/8xxx/CVE-2020-8334.json
  2020/8xxx/CVE-2020-8336.json
  2020/8xxx/CVE-2020-8337.json
Labels: accepted

#4021 TS already live
  2019/3xxx/CVE-2019-3617.json
Labels: accepted

#4023 Publish CVE-2019-3613
  2019/3xxx/CVE-2019-3613.json
Labels: accepted

#4024 Publish CVE-2020-7279
  2020/7xxx/CVE-2020-7279.json
Labels: accepted

#4026 Publish CVE-2019-3585
  2019/3xxx/CVE-2019-3585.json
Labels: accepted

#4027 CVE-2019-3588
  2019/3xxx/CVE-2019-3588.json
Labels: accepted

#4028 Publish CVE-2020-7280
  2020/7xxx/CVE-2020-7280.json
Labels: accepted

#4034 add CVE-2020-11090 for GHSA-3gw4-m5w7-v89c
  2020/11xxx/CVE-2020-11090.json
Labels: accepted

#4036 JPCERT/CC batch
  2020/5xxx/CVE-2020-5592.json
  2020/5xxx/CVE-2020-5593.json
Labels: accepted

#4038 Ibm20200611 893
  2020/4xxx/CVE-2020-4380.json
Labels: accepted

#4039 Add CVE-2020-5411
  2020/5xxx/CVE-2020-5411.json
Labels: accepted

#4040 add CVE-2020-4045 for GHSA-mpgr-2cx9-327h
  2020/4xxx/CVE-2020-4045.json
Labels: accepted

#4041 Add TWCERT/CC CVE-2020-3928 CVE-2020-3929 CVE-2020-3930
  2020/3xxx/CVE-2020-3928.json
  2020/3xxx/CVE-2020-3929.json
  2020/3xxx/CVE-2020-3930.json
Labels: accepted

#4042 Ibm20200612 9844
  2020/4xxx/CVE-2020-4251.json
Labels: accepted

#4043 add CVE-2020-4046 for GHSA-rpwf-hrh2-39jf
  2020/4xxx/CVE-2020-4046.json
Labels: accepted

#4047 add CVE-2020-4050 for GHSA-4vpv-fgg2-gcqc
  2020/4xxx/CVE-2020-4050.json
Labels: accepted

#4046 add CVE-2020-4049 for GHSA-87h4-phjv-rm6p
  2020/4xxx/CVE-2020-4049.json
Labels: accepted

#4045 add CVE-2020-4048 for GHSA-q6pw-gvf4-5fj5
  2020/4xxx/CVE-2020-4048.json
Labels: accepted

#4044 add CVE-2020-4047 for GHSA-8q2w-5m27-wm27
  2020/4xxx/CVE-2020-4047.json
Labels: accepted

#4048 Ibm20200615 92122
  2020/4xxx/CVE-2020-4216.json
  2020/4xxx/CVE-2020-4406.json
  2020/4xxx/CVE-2020-4469.json
  2020/4xxx/CVE-2020-4470.json
  2020/4xxx/CVE-2020-4471.json
  2020/4xxx/CVE-2020-4477.json
  2020/4xxx/CVE-2020-4494.json
Labels: accepted

#4049 Added CVE-2020-5358
  2020/5xxx/CVE-2020-5358.json
Labels: accepted

#4050 Add CVE-2020-4051 for GHSA-cxjc-r2fp-7mq6
  2020/4xxx/CVE-2020-4051.json
Labels: accepted

#4051 initial CVE-2020-12493 entry
  2020/12xxx/CVE-2020-12494.json
Labels: accepted

#4052 Ibm20200616 94329
  2020/4xxx/CVE-2020-4310.json
  2020/4xxx/CVE-2020-4320.json
Labels: accepted

#4053 Assign CVE-2020-10268
  2020/10xxx/CVE-2020-10268.json
Labels: accepted

#4054 add CVE-2020-4052 for GHSA-9jgg-4xj2-vjjj
  2020/4xxx/CVE-2020-4052.json
Labels: accepted

#4056 add CVE-2020-4053 for GHSA-qq3j-xp49-j73f
  2020/4xxx/CVE-2020-4053.json
Labels: accepted

#4057 add CVE-2020-4054 for GHSA-p4x4-rw2p-8j8m
  2020/4xxx/CVE-2020-4054.json
Labels: accepted

#4055 Bill Situ <Bill.Situ@Oracle.com>
  2020/2xxx/CVE-2020-2801.json
Labels: accepted

#4060 Ibm20200617 133911
  2020/4xxx/CVE-2020-4532.json
Labels: accepted

#4061 [ISC] document BIND9 CVE-2020-8618 CVE-2020-8619
  2020/8xxx/CVE-2020-8618.json
  2020/8xxx/CVE-2020-8619.json
Labels: accepted

#4094 Adding Cisco CVE-2020-3277
  2020/3xxx/CVE-2020-3277.json
Labels: accepted

#4093 Adding Cisco CVE-2020-3278
  2020/3xxx/CVE-2020-3278.json
Labels: accepted

#4092 Adding Cisco CVE-2020-3279
  2020/3xxx/CVE-2020-3279.json
Labels: accepted

#4091 Adding Cisco CVE-2020-3286
  2020/3xxx/CVE-2020-3286.json
Labels: accepted

#4090 Adding Cisco CVE-2020-3287
  2020/3xxx/CVE-2020-3287.json
Labels: accepted

#4089 Adding Cisco CVE-2020-3288
  2020/3xxx/CVE-2020-3288.json
Labels: accepted

#4088 Adding Cisco CVE-2020-3289
  2020/3xxx/CVE-2020-3289.json
Labels: accepted

#4087 Adding Cisco CVE-2020-3290
  2020/3xxx/CVE-2020-3290.json
Labels: accepted

#4086 Adding Cisco CVE-2020-3291
  2020/3xxx/CVE-2020-3291.json
Labels: accepted

#4085 Adding Cisco CVE-2020-3292
  2020/3xxx/CVE-2020-3292.json
Labels: accepted

#4084 Adding Cisco CVE-2020-3293
  2020/3xxx/CVE-2020-3293.json
Labels: accepted

#4083 Adding Cisco CVE-2020-3294
  2020/3xxx/CVE-2020-3294.json
Labels: accepted

#4082 Adding Cisco CVE-2020-3295
  2020/3xxx/CVE-2020-3295.json
Labels: accepted

#4081 Adding Cisco CVE-2020-3296
  2020/3xxx/CVE-2020-3296.json
Labels: accepted

#4080 Adding Cisco CVE-2020-3336
  2020/3xxx/CVE-2020-3336.json
Labels: accepted

#4079 Adding Cisco CVE-2020-3337
  2020/3xxx/CVE-2020-3337.json
Labels: accepted

#4078 Adding Cisco CVE-2020-3342
  2020/3xxx/CVE-2020-3342.json
Labels: accepted

#4077 Adding Cisco CVE-2020-3347
  2020/3xxx/CVE-2020-3347.json
Labels: accepted

#4076 Adding Cisco CVE-2020-3350
  2020/3xxx/CVE-2020-3350.json
Labels: accepted

#4075 Adding Cisco CVE-2020-3354
  2020/3xxx/CVE-2020-3354.json
Labels: accepted

#4074 Adding Cisco CVE-2020-3355
  2020/3xxx/CVE-2020-3355.json
Labels: accepted

#4073 Adding Cisco CVE-2020-3356
  2020/3xxx/CVE-2020-3356.json
Labels: accepted

#4072 Adding Cisco CVE-2020-3360
  2020/3xxx/CVE-2020-3360.json
Labels: accepted

#4071 Adding Cisco CVE-2020-3361
  2020/3xxx/CVE-2020-3361.json
Labels: accepted

#4070 Adding Cisco CVE-2020-3362
  2020/3xxx/CVE-2020-3362.json
Labels: accepted

#4069 Adding Cisco CVE-2020-3364
  2020/3xxx/CVE-2020-3364.json
Labels: accepted

#4068 Adding Cisco CVE-2020-3368
  2020/3xxx/CVE-2020-3368.json
Labels: accepted

#4105 Adding Cisco CVE-2020-3236
  2020/3xxx/CVE-2020-3236.json
Labels: accepted

#4104 Adding Cisco CVE-2020-3241
  2020/3xxx/CVE-2020-3241.json
Labels: accepted

#4103 Adding Cisco CVE-2020-3242
  2020/3xxx/CVE-2020-3242.json
Labels: accepted

#4102 Adding Cisco CVE-2020-3244
  2020/3xxx/CVE-2020-3244.json
Labels: accepted

#4101 Adding Cisco CVE-2020-3245
  2020/3xxx/CVE-2020-3245.json
Labels: accepted

#4100 Adding Cisco CVE-2020-3263
  2020/3xxx/CVE-2020-3263.json
Labels: accepted

#4099 Adding Cisco CVE-2020-3268
  2020/3xxx/CVE-2020-3268.json
Labels: accepted

#4098 Adding Cisco CVE-2020-3269
  2020/3xxx/CVE-2020-3269.json
Labels: accepted

#4097 Adding Cisco CVE-2020-3274
  2020/3xxx/CVE-2020-3274.json
Labels: accepted

#4096 Adding Cisco CVE-2020-3275
  2020/3xxx/CVE-2020-3275.json
Labels: accepted

#4095 Adding Cisco CVE-2020-3276
  2020/3xxx/CVE-2020-3276.json
Labels: accepted

#4062 CVE-2020-10782
  2020/10xxx/CVE-2020-10782.json
Labels: accepted

#4122 add CVE-2020-4059 for GHSA-qjg4-w4c6-f6c6
  2020/4xxx/CVE-2020-4059.json
Labels: accepted

#4125 JPCERT/CC CVE-2020-5590
  2020/5xxx/CVE-2020-5590.json
Labels: accepted

#4126 fixed encoding/charset problem
  2020/12xxx/CVE-2020-12494.json
Labels: accepted

#4129 Ibm20200619 12415
  2020/4xxx/CVE-2020-4281.json
  2020/4xxx/CVE-2020-4295.json
  2020/4xxx/CVE-2020-4297.json
Labels: accepted

#4130 CVE-2020-10750
  2020/10xxx/CVE-2020-10750.json
Labels: accepted
