Repository CVEProject/cvelist, pull requests merged in 2020-03, with the labels that each got.

#3333 JPCERT/CC CVE-2020-5539
  2020/5xxx/CVE-2020-5539.json
Labels: accepted

#3335 Ibm20200302 85421
  2020/4xxx/CVE-2020-4283.json
  2020/4xxx/CVE-2020-4292.json
Labels: accepted

#3337 add CVE-2020-5249 for GHSA-33vf-4xgg-9r58
  2020/5xxx/CVE-2020-5249.json
Labels: accepted

#3336 data for CVE-2019-18897
  2019/18xxx/CVE-2019-18897.json
Labels: accepted

#3338 data for CVE-2019-18901
  2019/18xxx/CVE-2019-18901.json
Labels: accepted

#3322 CVE-2020-1731 init
  2020/1xxx/CVE-2020-1731.json
Labels: accepted

#3334 CVE-2019-14892 init.
  2019/14xxx/CVE-2019-14892.json
Labels: accepted

#3340 data for CVE-2020-8013
  2020/8xxx/CVE-2020-8013.json
Labels: accepted

#3341 data for CVE-2019-18902, CVE-2019-18903
  2019/18xxx/CVE-2019-18902.json
  2019/18xxx/CVE-2019-18903.json
Labels: accepted

#3339 update description of CVE-2020-5247 - correct version
  2020/5xxx/CVE-2020-5247.json
Labels: accepted

#3342 CVE-2019-14893 init.
  2019/14xxx/CVE-2019-14893.json
Labels: accepted

#3343 CVE-2020-9751
  2020/9xxx/CVE-2020-9751.json
Labels: accepted

#3344 data for CVE-2019-3695, CVE-2019-3696
  2019/3xxx/CVE-2019-3695.json
  2019/3xxx/CVE-2019-3696.json
Labels: accepted

#3345 Ibm20200303 8476
  2020/4xxx/CVE-2020-4196.json
  2020/4xxx/CVE-2020-4197.json
  2020/4xxx/CVE-2020-4198.json
Labels: accepted

#3346 CVEs for latest HHVM release
  2020/1xxx/CVE-2020-1888.json
  2020/1xxx/CVE-2020-1892.json
  2020/1xxx/CVE-2020-1893.json
Labels: accepted

#3347 Add CVE-2020-5404
  2020/5xxx/CVE-2020-5404.json
Labels: accepted

#3348 Add CVE-2020-5403
  2020/5xxx/CVE-2020-5403.json
Labels: accepted

#3327 CVE-2020-1734 init.
  2020/1xxx/CVE-2020-1734.json
Labels: question

#3349 JPCERT/CC 2020-03-04
  2020/5xxx/CVE-2020-5535.json
  2020/5xxx/CVE-2020-5536.json
Labels: accepted

#3350 add CVE-2020-5251 for GHSA-h4mf-75hf-67w4
  2020/5xxx/CVE-2020-5251.json
Labels: accepted

#3358 Adding Cisco CVE-2020-3181
  2020/3xxx/CVE-2020-3181.json
Labels: accepted

#3357 Adding Cisco CVE-2020-3182
  2020/3xxx/CVE-2020-3182.json
Labels: accepted

#3355 Adding Cisco CVE-2020-3190
  2020/3xxx/CVE-2020-3190.json
Labels: accepted

#3354 Adding Cisco CVE-2020-3192
  2020/3xxx/CVE-2020-3192.json
Labels: accepted

#3353 Adding Cisco CVE-2020-3193
  2020/3xxx/CVE-2020-3193.json
Labels: accepted

#3365 Adding Cisco CVE-2020-3127
  2020/3xxx/CVE-2020-3127.json
Labels: accepted

#3364 Adding Cisco CVE-2020-3128
  2020/3xxx/CVE-2020-3128.json
Labels: accepted

#3363 Adding Cisco CVE-2020-3148
  2020/3xxx/CVE-2020-3148.json
Labels: accepted

#3362 Adding Cisco CVE-2020-3155
  2020/3xxx/CVE-2020-3155.json
Labels: accepted

#3361 Adding Cisco CVE-2020-3157
  2020/3xxx/CVE-2020-3157.json
Labels: accepted

#3360 Adding Cisco CVE-2020-3164
  2020/3xxx/CVE-2020-3164.json
Labels: accepted

#3359 Adding Cisco CVE-2020-3176
  2020/3xxx/CVE-2020-3176.json
Labels: accepted

#3366 CVE for VU#498544
  2020/9xxx/CVE-2020-9054.json
Labels: accepted

#3369 Ibm20200305 101628
  2020/4xxx/CVE-2020-4278.json
Labels: accepted

#3370 add CVE-2020-5250 for GHSA-mhfc-6rhg-fxp3
  2020/5xxx/CVE-2020-5250.json
Labels: accepted

#3351 CVE-2019-14886 init
  2019/14xxx/CVE-2019-14886.json
Labels: accepted

#3371 Add CVE-2020-5405
  2020/5xxx/CVE-2020-5405.json
Labels: accepted

#3367 Update CVE-2020-5957.json
  2020/5xxx/CVE-2020-5957.json
Labels: accepted

#3372 Added CVE-2020-5327,5328
  2020/5xxx/CVE-2020-5327.json
  2020/5xxx/CVE-2020-5328.json
Labels: accepted

#3375 Ibm20200309 103417
  2020/4xxx/CVE-2020-4217.json
Labels: accepted

#3086 CVE-2020-1706 init
  2020/1xxx/CVE-2020-1706.json
Labels: needs-work

#3376 Add CVEs for 2020-03-09 Jenkins security advisory
  2020/2xxx/CVE-2020-2134.json
  2020/2xxx/CVE-2020-2135.json
  2020/2xxx/CVE-2020-2136.json
  2020/2xxx/CVE-2020-2137.json
  2020/2xxx/CVE-2020-2138.json
  2020/2xxx/CVE-2020-2139.json
  2020/2xxx/CVE-2020-2140.json
  2020/2xxx/CVE-2020-2141.json
  2020/2xxx/CVE-2020-2142.json
  2020/2xxx/CVE-2020-2143.json
  2020/2xxx/CVE-2020-2144.json
  2020/2xxx/CVE-2020-2145.json
  2020/2xxx/CVE-2020-2146.json
  2020/2xxx/CVE-2020-2147.json
  2020/2xxx/CVE-2020-2148.json
  2020/2xxx/CVE-2020-2149.json
  2020/2xxx/CVE-2020-2150.json
  2020/2xxx/CVE-2020-2151.json
  2020/2xxx/CVE-2020-2152.json
  2020/2xxx/CVE-2020-2153.json
  2020/2xxx/CVE-2020-2154.json
  2020/2xxx/CVE-2020-2155.json
  2020/2xxx/CVE-2020-2156.json
  2020/2xxx/CVE-2020-2157.json
  2020/2xxx/CVE-2020-2158.json
  2020/2xxx/CVE-2020-2159.json
Labels: accepted

#3352 CVE-2020-1737 init.
  2020/1xxx/CVE-2020-1737.json
Labels: needs work

#3377 add CVE-2020-5256 for GHSA-g9rq-x4fj-f5hx
  2020/5xxx/CVE-2020-5256.json
Labels: accepted

#3378 Added CVE-2020-5342
  2020/5xxx/CVE-2020-5342.json
Labels: accepted

#3380 Ibm20200310 7506
  2019/4xxx/CVE-2019-4608.json
  2020/4xxx/CVE-2020-4162.json
Labels: accepted

#3381 CVE-2019-17636
  2019/17xxx/CVE-2019-17636.json
Labels: accepted

#3382 add CVE-2020-5253 for GHSA-2c7p-3fj4-223m
  2020/5xxx/CVE-2020-5253.json
Labels: accepted

#3383 add CVE-2020-5254 for GHSA-2ch6-6r8h-m2p9
  2020/5xxx/CVE-2020-5254.json
Labels: accepted

#3385 add CVE-2020-5259 for GHSA-3hw5-q855-g6cw
  2020/5xxx/CVE-2020-5259.json
Labels: accepted

#3384 add CVE-2020-5258 for GHSA-jxfh-8wgv-vfr2
  2020/5xxx/CVE-2020-5258.json
Labels: accepted

#3386 Publish CVE-2019-3553 and CVE-2019-11938
  2019/11xxx/CVE-2019-11938.json
  2019/3xxx/CVE-2019-3553.json
Labels: accepted

#3389 TIBCO Software Inc. security advisory for TIBCO Spotfire Server.
  2020/9xxx/CVE-2020-9408.json
Labels: accepted

#3391 Publish CVE-2020-7253
  2020/7xxx/CVE-2020-7253.json
Labels: accepted

#3392 Publish CVE-2020-7254
  2020/7xxx/CVE-2020-7254.json
Labels: accepted

#3393 Add info for CVE-2019-5648
  2019/5xxx/CVE-2019-5648.json
Labels: accepted

#3398 NVIDIA CVE assignments for GPU Display Driver - February 2020
  2020/5xxx/CVE-2020-5959.json
  2020/5xxx/CVE-2020-5960.json
  2020/5xxx/CVE-2020-5961.json
Labels: accepted

#3399 CVE-2020-8469 Trend Micro
  2020/8xxx/CVE-2020-8469.json
Labels: accepted

#3400 Add CVE-2020-1887
  2020/1xxx/CVE-2020-1887.json
Labels: accepted

#3401 Update CVE-2019-19756.json
  2019/19xxx/CVE-2019-19756.json
Labels: accepted

#3403 add CVE-2020-5257 for GHSA-2p5p-m353-833w
  2020/5xxx/CVE-2020-5257.json
Labels: accepted

#3404 add CVE-2020-5240 for GHSA-9gjv-6qq6-v7qm
  2020/5xxx/CVE-2020-5240.json
Labels: accepted

#3405 JPCERT/CC 2020-03-16
  2020/5xxx/CVE-2020-5542.json
  2020/5xxx/CVE-2020-5543.json
  2020/5xxx/CVE-2020-5544.json
  2020/5xxx/CVE-2020-5545.json
  2020/5xxx/CVE-2020-5546.json
  2020/5xxx/CVE-2020-5547.json
Labels: accepted

#3260 CVE-2020-1735
  2020/1xxx/CVE-2020-1735.json
Labels: needs work

#3259 CVE-2020-1740
  2020/1xxx/CVE-2020-1740.json
Labels: needs work

#3258 CVE-2020-1738
  2020/1xxx/CVE-2020-1738.json
Labels: needs work

#3261 CVE-2020-1736
  2020/1xxx/CVE-2020-1736.json
Labels: needs work

#3409 Ibm20200316 112319
  2019/4xxx/CVE-2019-4617.json
  2019/4xxx/CVE-2019-4619.json
  2019/4xxx/CVE-2019-4656.json
  2019/4xxx/CVE-2019-4719.json
Labels: accepted

#3410 Add CVE-2019-20105
  2019/20xxx/CVE-2019-20105.json
Labels: accepted

#3411 Add CVE-2019-20407
  2019/20xxx/CVE-2019-20407.json
Labels: accepted

#3415 Trend Micro CVE-2020-8467, 8468, 8470, 8598, 8599, 8600
  2020/8xxx/CVE-2020-8467.json
  2020/8xxx/CVE-2020-8468.json
  2020/8xxx/CVE-2020-8470.json
  2020/8xxx/CVE-2020-8598.json
  2020/8xxx/CVE-2020-8599.json
  2020/8xxx/CVE-2020-8600.json
Labels: accepted

#3416 Publish CVE-2019-11939
  2019/11xxx/CVE-2019-11939.json
Labels: accepted

#3417 Add TWCERT/CC CVE-2020-3922
  2020/3xxx/CVE-2020-3922.json
Labels: accepted

#3060 CVE-2019-14882 update
  2019/14xxx/CVE-2019-14882.json
Labels: needs-work

#3059 CVE-2019-14881 update
  2019/14xxx/CVE-2019-14881.json
Labels: needs-work

#3061 CVE-2019-14883 update
  2019/14xxx/CVE-2019-14883.json
Labels: needs-work

#3062 CVE-2019-14884 update
  2019/14xxx/.CVE-2019-14886.json.swp
  2019/14xxx/CVE-2019-14884.json
Labels: needs-work

#3418 Ibm20200318 95115
  2020/4xxx/CVE-2020-4199.json
Labels: accepted

#3189 CVE-2019-10146 update
  2019/10xxx/CVE-2019-10146.json
Labels: needs work

#3196 CVE-2019-10178 update
  2019/10xxx/CVE-2019-10178.json
Labels: needs work

#3431 Update CVE-2020-7258.json
  2020/7xxx/CVE-2020-7258.json
Labels: accepted

#3430 Update CVE-2020-7256.json
  2020/7xxx/CVE-2020-7256.json
Labels: accepted

#3438 Ibm20200319 9377
  2020/4xxx/CVE-2020-4203.json
  2020/4xxx/CVE-2020-4205.json
Labels: accepted

#3193 CVE-2020-1705 update
  2020/1xxx/CVE-2020-1705.json
Labels: needs work

#3444 Adding Cisco CVE-2020-3266
  2020/3xxx/CVE-2020-3266.json
Labels: accepted

#3443 Adding Cisco CVE-2020-3265
  2020/3xxx/CVE-2020-3265.json
Labels: accepted

#3442 Adding Cisco CVE-2020-3264
  2020/3xxx/CVE-2020-3264.json
Labels: accepted

#3441 Adding Cisco CVE-2019-16012
  2019/16xxx/CVE-2019-16012.json
Labels: accepted

#3440 Adding Cisco CVE-2019-16010
  2019/16xxx/CVE-2019-16010.json
Labels: accepted

#3445 add CVE-2020-5262 for GHSA-2wx6-wc87-rmjm
  2020/5xxx/CVE-2020-5262.json
Labels: accepted

#3446 add CVE-2020-5267 for GHSA-65cv-r6x7-79hv
  2020/5xxx/CVE-2020-5267.json
Labels: accepted

#3186 CVE-2019-10179 update
  2019/10xxx/CVE-2019-10179.json
Labels: needs work

#3188 CVE-2020-1696 update
  2020/1xxx/CVE-2020-1696.json
Labels: needs work

#3190 CVE-2019-10221 update
  2019/10xxx/CVE-2019-10221.json
Labels: needs work

#3192 CVE-2020-1707 update
  2020/1xxx/CVE-2020-1707.json
Labels: needs work

#3194 CVE-2020-1709 update
  2020/1xxx/CVE-2020-1709.json
Labels: needs work

#3195 CVE-2019-19345 update
  2019/19xxx/CVE-2019-19345.json
Labels: needs work

#3449 ZDI assigns the following Foxit CVEs:
  2020/8xxx/CVE-2020-8877.json
  2020/8xxx/CVE-2020-8878.json
  2020/8xxx/CVE-2020-8879.json
  2020/8xxx/CVE-2020-8880.json
  2020/8xxx/CVE-2020-8881.json
  2020/8xxx/CVE-2020-8882.json
  2020/8xxx/CVE-2020-8883.json
Labels: accepted

#3450 Update CVE-2020-9752.json
  2020/9xxx/CVE-2020-9752.json
Labels: accepted

#3451 Ibm20200323 102742
  2019/4xxx/CVE-2019-4718.json
Labels: accepted

#3453 ZDI assigns the following Parallels CVEs:
  2020/8xxx/CVE-2020-8871.json
  2020/8xxx/CVE-2020-8872.json
  2020/8xxx/CVE-2020-8873.json
  2020/8xxx/CVE-2020-8874.json
  2020/8xxx/CVE-2020-8875.json
  2020/8xxx/CVE-2020-8876.json
Labels: accepted

#3454 ZDI assigns the following CVEs:
  2020/8xxx/CVE-2020-8865.json
  2020/8xxx/CVE-2020-8866.json
  2020/8xxx/CVE-2020-8868.json
Labels: accepted

#3455 ZDI assigns the following CVEs:
  2020/8xxx/CVE-2020-8859.json
  2020/8xxx/CVE-2020-8863.json
  2020/8xxx/CVE-2020-8864.json
Labels: accepted

#3456 add CVE-2020-5252 for GHSA-7q25-qrjw-6fg2
  2020/5xxx/CVE-2020-5252.json
Labels: accepted

#3458 CVE-2020-1744 init
  2020/1xxx/CVE-2020-1744.json
Labels: accepted

#3459 CVE-2020-10684 init
  2020/10xxx/CVE-2020-10684.json
Labels: accepted

#3460 CVE-2020-1747 init.
  2020/1xxx/CVE-2020-1747.json
Labels: accepted

#3461 Ibm20200324 111412
  2019/4xxx/CVE-2019-4553.json
  2019/4xxx/CVE-2019-4681.json
  2020/4xxx/CVE-2020-4253.json
  2020/4xxx/CVE-2020-4309.json
Labels: accepted

#3464 add CVE-2020-5261 for GHSA-g6j2-ch25-5mmv
  2020/5xxx/CVE-2020-5261.json
Labels: accepted

#3465 JPCERT/CC 2020-03-25
  2020/5xxx/CVE-2020-5552.json
  2020/5xxx/CVE-2020-5553.json
  2020/5xxx/CVE-2020-5554.json
  2020/5xxx/CVE-2020-5555.json
  2020/5xxx/CVE-2020-5556.json
  2020/5xxx/CVE-2020-5557.json
  2020/5xxx/CVE-2020-5558.json
  2020/5xxx/CVE-2020-5559.json
  2020/5xxx/CVE-2020-5560.json
  2020/5xxx/CVE-2020-5561.json
Labels: accepted

#3467 Add CVEs for 2020-03-25 Jenkins security advisory
  2020/2xxx/CVE-2020-2160.json
  2020/2xxx/CVE-2020-2161.json
  2020/2xxx/CVE-2020-2162.json
  2020/2xxx/CVE-2020-2163.json
  2020/2xxx/CVE-2020-2164.json
  2020/2xxx/CVE-2020-2165.json
  2020/2xxx/CVE-2020-2166.json
  2020/2xxx/CVE-2020-2167.json
  2020/2xxx/CVE-2020-2168.json
  2020/2xxx/CVE-2020-2169.json
  2020/2xxx/CVE-2020-2170.json
  2020/2xxx/CVE-2020-2171.json
Labels: accepted

#3468 add CVE-2020-5280 for GHSA-66q9-f7ff-mmx6
  2020/5xxx/CVE-2020-5280.json
Labels: accepted

#3469 add CVE-2020-5281 for GHSA-gj88-9q3f-72m3
  2020/5xxx/CVE-2020-5281.json
Labels: accepted

#3470 add CVE-2020-5282 for GHSA-8xwp-r7pj-cgw3
  2020/5xxx/CVE-2020-5282.json
Labels: accepted

#3471 add CVE-2020-5277 for GHSA-mmmv-m5q9-g3cm
  2020/5xxx/CVE-2020-5277.json
Labels: accepted

#3462 CVE-2020-8923
  2020/8xxx/CVE-2020-8923.json
Labels: accepted

#3457 Adding CVE-2020-8910
  2020/8xxx/CVE-2020-8910.json
Labels: accepted

#3474 Added CVE-2020-5339, 5340
  2020/5xxx/CVE-2020-5339.json
  2020/5xxx/CVE-2020-5340.json
Labels: accepted

#3475 SonicWall SMA1000 DoS Vulnerability
  2020/5xxx/CVE-2020-5129.json
Labels: accepted

#3476 CVE-2020-1764 init
  2020/1xxx/CVE-2020-1764.json
Labels: accepted

#3477 Publish CVE-2020-7260.json
  2020/7xxx/CVE-2020-7260.json
Labels: accepted

#3473 python-apt issues
  2019/15xxx/CVE-2019-15795.json
  2019/15xxx/CVE-2019-15796.json
Labels: accepted

#3479 Ibm20200326 91819
  2020/4xxx/CVE-2020-4276.json
Labels: accepted

#3480 Add TWCERT/CC CVE-2020-3920 CVE-2020-3921 CVE-2020-3936
  2020/3xxx/CVE-2020-3920.json
  2020/3xxx/CVE-2020-3921.json
  2020/3xxx/CVE-2020-3936.json
Labels: accepted

#3481 Add TWCERT/CC CVE-2020-10508 CVE-2020-10509 CVE-2020-10510
  2020/10xxx/CVE-2020-10508.json
  2020/10xxx/CVE-2020-10509.json
  2020/10xxx/CVE-2020-10510.json
Labels: accepted

#3463 CVE-2020-8551 and CVE-2020-8552
  2020/8xxx/CVE-2020-8551.json
  2020/8xxx/CVE-2020-8552.json
Labels: accepted

#3485 JPCERT/CC CVE-2020-5551
  2020/5xxx/CVE-2020-5551.json
Labels: accepted

#3486 JPCERT/CC CVE-2020-5527
  2020/5xxx/CVE-2020-5527.json
Labels: accepted

#3488 add CVE-2020-5255 for GHSA-mcx4-f5f5-4859
  2020/5xxx/CVE-2020-5255.json
Labels: accepted

#3489 add CVE-2020-5274 for GHSA-m884-279h-32v2
  2020/5xxx/CVE-2020-5274.json
Labels: accepted

#3490 add CVE-2020-5275 for GHSA-g4m9-5hpf-hx72
  2020/5xxx/CVE-2020-5275.json
Labels: accepted

#3492 add CVE-2020-5284 for GHSA-fq77-7p7r-83rj
  2020/5xxx/CVE-2020-5284.json
Labels: accepted

#3493 CVEs for VU#962085 and VU#944837
  2019/9xxx/CVE-2019-9507.json
  2019/9xxx/CVE-2019-9508.json
  2019/9xxx/CVE-2019-9509.json
  2020/9xxx/CVE-2020-9055.json
Labels: accepted

#3494 add CVE-2020-5289 for GHSA-2mxr-89gf-rc4v
  2020/5xxx/CVE-2020-5289.json
Labels: accepted

#3498 Add CVE-2019-2391
  2019/2xxx/CVE-2019-2391.json
Labels: accepted

#3500 Ibm20200331 10242
  2020/4xxx/CVE-2020-4206.json
  2020/4xxx/CVE-2020-4208.json
  2020/4xxx/CVE-2020-4214.json
  2020/4xxx/CVE-2020-4235.json
  2020/4xxx/CVE-2020-4236.json
  2020/4xxx/CVE-2020-4237.json
  2020/4xxx/CVE-2020-4238.json
  2020/4xxx/CVE-2020-4239.json
  2020/4xxx/CVE-2020-4240.json
  2020/4xxx/CVE-2020-4241.json
  2020/4xxx/CVE-2020-4242.json
Labels: accepted

#3057 CVE-2019-14879 update
  2019/14xxx/CVE-2019-14879.json
Labels: needs-work

#3058 CVE-2019-14880 update
  2019/14xxx/CVE-2019-14880.json
Labels: needs-work

#3124 Cve 2019 14905
  2019/14xxx/CVE-2019-14905.json
Labels: needs work

#3191 CVE-2019-10180 update
  2019/10xxx/CVE-2019-10180.json
Labels: needs work

#3197 CVE-2020-1712 update
  2020/1xxx/CVE-2020-1712.json
Labels: needs work

#3502 add CVE-2020-5291 for GHSA-j2qp-rvxj-43vj
  2020/5xxx/CVE-2020-5291.json
Labels: accepted

#3503 add CVE-2020-5292 for GHSA-ww6x-rhvp-55hp
  2020/5xxx/CVE-2020-5292.json
Labels: accepted

#3504 Add Elasticsearch CVE
  2020/7xxx/CVE-2020-7009.json
Labels: accepted

#3507 Added CVE-2020-5344
  2020/5xxx/CVE-2020-5344.json
Labels: accepted
