Repository CVEProject/cvelist, pull requests merged in 2020-04, with the labels that each got.

#3508 PHP issues from March release
  2020/7xxx/CVE-2020-7064.json
  2020/7xxx/CVE-2020-7065.json
  2020/7xxx/CVE-2020-7066.json
Labels: accepted

#3509 Publish CVE-2020-7263
  2020/7xxx/CVE-2020-7263.json
Labels: accepted

#3510 JPCERT/CC CVE-2020-5548
  2020/5xxx/CVE-2020-5548.json
Labels: accepted

#3515 add CVE-2020-5290 for GHSA-p5fh-2vhw-fvpq
  2020/5xxx/CVE-2020-5290.json
Labels: accepted

#3516 CVE-2019-11254
  2019/11xxx/CVE-2019-11254.json
Labels: accepted

#3517 data for CVE-2020-8015
  2020/8xxx/CVE-2020-8015.json
Labels: accepted

#3519 data for CVE-2020-8016, CVE-2020-8017
  2020/8xxx/CVE-2020-8016.json
  2020/8xxx/CVE-2020-8017.json
Labels: accepted

#3520 Ibm20200402 101346
  2020/4xxx/CVE-2020-4303.json
  2020/4xxx/CVE-2020-4304.json
  2020/4xxx/CVE-2020-4325.json
Labels: accepted

#3419 Added CVE-2019-14868
  2019/14xxx/CVE-2019-14868.json
Labels: missing version, needs-work

#3501 Canonical CNA: add CVE-2020-8835 / linux kernel / USN-4313-1
  2020/8xxx/CVE-2020-8835.json
Labels: accepted

#3512 Add CVE-2020-7617
  2020/7xxx/CVE-2020-7617.json
Labels: accepted

#3522 add CVE-2020-5283 for GHSA-xpxf-fvqv-7mfg
  2020/5xxx/CVE-2020-5283.json
Labels: accepted

#3523 data for CVE-2018-17954
  2018/17xxx/CVE-2018-17954.json
Labels: accepted

#3524 data for CVE-2019-18904
  2019/18xxx/CVE-2019-18904.json
Labels: accepted

#3525 data for CVE-2019-18905
  2019/18xxx/CVE-2019-18905.json
Labels: accepted

#3526 Ibm20200403 83339
  2020/4xxx/CVE-2020-4273.json
Labels: accepted

#3527 Added CVE-2020-5347,5348
  2020/5xxx/CVE-2020-5347.json
  2020/5xxx/CVE-2020-5348.json
Labels: accepted

#3514 Update CVE-2020-10264.json
  2020/10xxx/CVE-2020-10264.json
Labels: needs work

#3412 Cve 2020 1728
  2020/1xxx/CVE-2020-1728.json
Labels: missing version, needs-work

#3531 add CVE-2020-5300 for GHSA-3p3g-vpw6-4w66
  2020/5xxx/CVE-2020-5300.json
Labels: accepted

#3532 Added information for CVE-2020-8096
  2020/8xxx/CVE-2020-8096.json
Labels: accepted

#3533 Add CVEs for Jenkins 2020-04-07 security advisory
  2020/2xxx/CVE-2020-2172.json
  2020/2xxx/CVE-2020-2173.json
  2020/2xxx/CVE-2020-2174.json
  2020/2xxx/CVE-2020-2175.json
  2020/2xxx/CVE-2020-2176.json
Labels: accepted

#3534 add CVE-2020-5302 for GHSA-7hf3-wvp8-34r9
  2020/5xxx/CVE-2020-5302.json
Labels: accepted

#3536 Microk8s issue
  2019/15xxx/CVE-2019-15789.json
Labels: accepted

#3537 JPCERT/CC 2020-04-08
  2020/5xxx/CVE-2020-5549.json
  2020/5xxx/CVE-2020-5550.json
Labels: accepted

#3538 Ibm20200408 9595
  2019/4xxx/CVE-2019-4601.json
  2019/4xxx/CVE-2019-4602.json
  2019/4xxx/CVE-2019-4603.json
  2019/4xxx/CVE-2019-4737.json
  2019/4xxx/CVE-2019-4740.json
  2019/4xxx/CVE-2019-4746.json
  2020/4xxx/CVE-2020-4164.json
  2020/4xxx/CVE-2020-4252.json
  2020/4xxx/CVE-2020-4282.json
  2020/4xxx/CVE-2020-4284.json
  2020/4xxx/CVE-2020-4289.json
  2020/4xxx/CVE-2020-4290.json
  2020/4xxx/CVE-2020-4291.json
Labels: accepted

#3539 add CVE-2020-11000 for GHSA-7x3j-7x5w-8g7w
  2020/11xxx/CVE-2020-11000.json
Labels: accepted

#3541 juniper-2020-04-08 CVE publications
  2020/1xxx/CVE-2020-1613.json
  2020/1xxx/CVE-2020-1614.json
  2020/1xxx/CVE-2020-1615.json
  2020/1xxx/CVE-2020-1616.json
  2020/1xxx/CVE-2020-1617.json
  2020/1xxx/CVE-2020-1618.json
  2020/1xxx/CVE-2020-1619.json
  2020/1xxx/CVE-2020-1620.json
  2020/1xxx/CVE-2020-1621.json
  2020/1xxx/CVE-2020-1622.json
  2020/1xxx/CVE-2020-1623.json
  2020/1xxx/CVE-2020-1624.json
  2020/1xxx/CVE-2020-1625.json
  2020/1xxx/CVE-2020-1626.json
  2020/1xxx/CVE-2020-1627.json
  2020/1xxx/CVE-2020-1628.json
  2020/1xxx/CVE-2020-1629.json
  2020/1xxx/CVE-2020-1630.json
  2020/1xxx/CVE-2020-1634.json
  2020/1xxx/CVE-2020-1637.json
  2020/1xxx/CVE-2020-1638.json
  2020/1xxx/CVE-2020-1639.json
Labels: accepted

#3543 Adding CVE-2020-1885
  2020/1xxx/CVE-2020-1885.json
Labels: accepted

#3535 Bill Situ <Bill.Situ@Oracle.com>
  2020/2xxx/CVE-2020-2732.json
Labels: accepted

#3547 add CVE-2020-5263 for GHSA-prfq-f66g-43mp
  2020/5xxx/CVE-2020-5263.json
Labels: accepted

#3548 Add CVE-2020-1895
  2020/1xxx/CVE-2020-1895.json
Labels: accepted

#3549 Add CVE-2020-7922
  2020/7xxx/CVE-2020-7922.json
Labels: accepted

#3550 Canonical CNA: add info for CVE-2020-8834
  2020/8xxx/CVE-2020-8834.json
Labels: accepted

#3551 Canonical CNA: add info for CVE-2020-8832
  2020/8xxx/CVE-2020-8832.json
Labels: accepted

#3552 CVE-2019-7305 - eXtplorer vulnerability
  2019/7xxx/CVE-2019-7305.json
Labels: accepted

#3553 Ibm20200410 95431
  2020/4xxx/CVE-2020-4362.json
Labels: accepted

#3554 add CVE-2020-5303 for GHSA-v24h-pjjv-mcp6
  2020/5xxx/CVE-2020-5303.json
Labels: accepted

#3556 add CVE-2020-11002 for GHSA-8jpx-m2wh-2v34
  2020/11xxx/CVE-2020-11002.json
Labels: accepted

#3555 CVE for VU#660597
  2020/9xxx/CVE-2020-9056.json
Labels: accepted

#3557 Add CVE-2020-5406
  2020/5xxx/CVE-2020-5406.json
Labels: accepted

#3558 Added CVE-2020-5330
  2020/5xxx/CVE-2020-5330.json
Labels: accepted

#3559 Added CVE-2020-1759
  2020/1xxx/CVE-2020-1759.json
Labels: accepted

#3560 Adding Cisco CVE-2020-3126
  2020/3xxx/CVE-2020-3126.json
Labels: accepted

#3562 Adding Cisco CVE-2019-1866
  2019/1xxx/CVE-2019-1866.json
Labels: accepted

#3563 Chrome 81 CVEs.
  2020/6xxx/CVE-2020-6423.json
  2020/6xxx/CVE-2020-6430.json
  2020/6xxx/CVE-2020-6431.json
  2020/6xxx/CVE-2020-6432.json
  2020/6xxx/CVE-2020-6433.json
  2020/6xxx/CVE-2020-6434.json
  2020/6xxx/CVE-2020-6435.json
  2020/6xxx/CVE-2020-6436.json
  2020/6xxx/CVE-2020-6437.json
  2020/6xxx/CVE-2020-6438.json
  2020/6xxx/CVE-2020-6439.json
  2020/6xxx/CVE-2020-6440.json
  2020/6xxx/CVE-2020-6441.json
  2020/6xxx/CVE-2020-6442.json
  2020/6xxx/CVE-2020-6443.json
  2020/6xxx/CVE-2020-6444.json
  2020/6xxx/CVE-2020-6445.json
  2020/6xxx/CVE-2020-6446.json
  2020/6xxx/CVE-2020-6447.json
  2020/6xxx/CVE-2020-6448.json
  2020/6xxx/CVE-2020-6450.json
  2020/6xxx/CVE-2020-6451.json
  2020/6xxx/CVE-2020-6452.json
  2020/6xxx/CVE-2020-6454.json
  2020/6xxx/CVE-2020-6455.json
  2020/6xxx/CVE-2020-6456.json
Labels: accepted

#3561 CVE-2020-1730 init.
  2020/1xxx/CVE-2020-1730.json
Labels: accepted

#3564 Ubuntu, add kernel snap build process using unverified apt sources
  2019/11xxx/CVE-2019-11480.json
Labels: accepted

#3566 Ibm20200414 1173
  2020/4xxx/CVE-2020-4151.json
Labels: accepted

#3565 Siemens CVE update for Siemens-AD-2020-04
  2019/10xxx/CVE-2019-10934.json
  2019/10xxx/CVE-2019-10936.json
  2019/10xxx/CVE-2019-10939.json
  2019/13xxx/CVE-2019-13940.json
  2019/19xxx/CVE-2019-19282.json
  2019/19xxx/CVE-2019-19300.json
  2019/19xxx/CVE-2019-19301.json
  2020/7xxx/CVE-2020-7574.json
  2020/7xxx/CVE-2020-7575.json
Labels: accepted

#3569 Lenovo April '20 Advisories
  2020/8xxx/CVE-2020-8316.json
  2020/8xxx/CVE-2020-8318.json
  2020/8xxx/CVE-2020-8319.json
  2020/8xxx/CVE-2020-8324.json
  2020/8xxx/CVE-2020-8327.json
Labels: accepted

#3571 add CVE-2020-11005 for GHSA-wvpv-ffcv-r6cw
  2020/11xxx/CVE-2020-11005.json
Labels: accepted

#3573 add CVE-2020-5260 for GHSA-qm7j-c969-7j4q
  2020/5xxx/CVE-2020-5260.json
Labels: accepted

#3574 add CVE-2020-11001 for GHSA-v2wc-pfq2-5cm6
  2020/11xxx/CVE-2020-11001.json
Labels: accepted

#3575 add CVE-2020-11003 for GHSA-j438-45hc-vjhm
  2020/11xxx/CVE-2020-11003.json
Labels: accepted

#3577 Add TWCERT/CC CVE-2020-10505 CVE-2020-10506 CVE-2020-10507
  2020/10xxx/CVE-2020-10505.json
  2020/10xxx/CVE-2020-10506.json
  2020/10xxx/CVE-2020-10507.json
Labels: accepted

#3578 Add TWCERT/CC CVE-2020-10513 CVE-2020-10514
  2020/10xxx/CVE-2020-10511.json
  2020/10xxx/CVE-2020-10512.json
  2020/10xxx/CVE-2020-10513.json
  2020/10xxx/CVE-2020-10514.json
  2020/3xxx/CVE-2020-3932.json
Labels: accepted

#3579 Publish CVE-2020-7278
  2020/7xxx/CVE-2020-7278.json
Labels: accepted

#3581 Publish CVE-2020-7276
  2020/7xxx/CVE-2020-7276.json
Labels: accepted

#3580 Publish CVE-2020-7277
  2020/7xxx/CVE-2020-7277.json
Labels: accepted

#3583 Publish CVE-2020-7274
  2020/7xxx/CVE-2020-7274.json
Labels: accepted

#3582 Publish CVE-2020-7275
  2020/7xxx/CVE-2020-7275.json
Labels: accepted

#3584 Publish CVE-2020-7273
  2020/7xxx/CVE-2020-7273.json
Labels: accepted

#3585 Publish CVE-2020-7261
  2020/7xxx/CVE-2020-7261.json
Labels: accepted

#3586 Publish CVE-2020-7259
  2020/7xxx/CVE-2020-7259.json
Labels: accepted

#3587 Publish CVE-2020-7257
  2020/7xxx/CVE-2020-7257.json
Labels: accepted

#3589 Publish CVE-2020-7250
  2020/7xxx/CVE-2020-7250.json
Labels: accepted

#3588 Publish CVE-2020-7255
  2020/7xxx/CVE-2020-7255.json
Labels: accepted

#3572 Added CVE-2020-10699
  2020/10xxx/CVE-2020-10699.json
Labels: accepted

#3590 Ibm20200415 11418
  2019/4xxx/CVE-2019-4593.json
  2019/4xxx/CVE-2019-4594.json
  2019/4xxx/CVE-2019-4654.json
  2020/4xxx/CVE-2020-4268.json
  2020/4xxx/CVE-2020-4269.json
  2020/4xxx/CVE-2020-4270.json
  2020/4xxx/CVE-2020-4271.json
  2020/4xxx/CVE-2020-4272.json
  2020/4xxx/CVE-2020-4274.json
  2020/4xxx/CVE-2020-4294.json
Labels: accepted

#3592 Added CVE-2020-5346,5350
  2020/5xxx/CVE-2020-5346.json
  2020/5xxx/CVE-2020-5350.json
Labels: accepted

#3609 Adding Cisco CVE-2020-3161
  2020/3xxx/CVE-2020-3161.json
Labels: accepted

#3608 Adding Cisco CVE-2020-3162
  2020/3xxx/CVE-2020-3162.json
Labels: accepted

#3607 Adding Cisco CVE-2020-3177
  2020/3xxx/CVE-2020-3177.json
Labels: accepted

#3606 Adding Cisco CVE-2020-3194
  2020/3xxx/CVE-2020-3194.json
Labels: accepted

#3605 Adding Cisco CVE-2020-3239
  2020/3xxx/CVE-2020-3239.json
Labels: accepted

#3604 Adding Cisco CVE-2020-3240
  2020/3xxx/CVE-2020-3240.json
Labels: accepted

#3603 Adding Cisco CVE-2020-3243
  2020/3xxx/CVE-2020-3243.json
Labels: accepted

#3602 Adding Cisco CVE-2020-3247
  2020/3xxx/CVE-2020-3247.json
Labels: accepted

#3601 Adding Cisco CVE-2020-3248
  2020/3xxx/CVE-2020-3248.json
Labels: accepted

#3600 Adding Cisco CVE-2020-3249
  2020/3xxx/CVE-2020-3249.json
Labels: accepted

#3599 Adding Cisco CVE-2020-3250
  2020/3xxx/CVE-2020-3250.json
Labels: accepted

#3598 Adding Cisco CVE-2020-3251
  2020/3xxx/CVE-2020-3251.json
Labels: accepted

#3597 Adding Cisco CVE-2020-3252
  2020/3xxx/CVE-2020-3252.json
Labels: accepted

#3596 Adding Cisco CVE-2020-3260
  2020/3xxx/CVE-2020-3260.json
Labels: accepted

#3595 Adding Cisco CVE-2020-3261
  2020/3xxx/CVE-2020-3261.json
Labels: accepted

#3594 Adding Cisco CVE-2020-3262
  2020/3xxx/CVE-2020-3262.json
Labels: accepted

#3593 Adding Cisco CVE-2020-3273
  2020/3xxx/CVE-2020-3273.json
Labels: accepted

#3610 Added missing CVE-2020-1632.
  2020/1xxx/CVE-2020-1632.json
Labels: accepted

#3612 Update CVE-2020-10505 CVE-2020-10507
  2020/10xxx/CVE-2020-10505.json
  2020/10xxx/CVE-2020-10507.json
Labels: accepted

#3614 Add CVE IDs for 2020-04-16 Jenkins security advisory
  2020/2xxx/CVE-2020-2177.json
  2020/2xxx/CVE-2020-2178.json
  2020/2xxx/CVE-2020-2179.json
  2020/2xxx/CVE-2020-2180.json
Labels: accepted

#3618 Ibm20200416 113232
  2019/4xxx/CVE-2019-4762.json
  2020/4xxx/CVE-2020-4260.json
  2020/4xxx/CVE-2020-4338.json
  2020/4xxx/CVE-2020-4347.json
Labels: accepted

#3615 Updating Cisco CVE-2016-1421
  2016/1xxx/CVE-2016-1421.json
Labels: accepted

#3620 add CVE-2020-11007 for GHSA-w8rc-pgxq-x2cj
  2020/11xxx/CVE-2020-11007.json
Labels: accepted

#3611 Add CVE-2020-5266 for GHSA-vr7g-vqp5-966j
  2020/5xxx/CVE-2020-5266.json
Labels: accepted

#3616 Add CVE-2020-5273 for GHSA-cx2r-mf6x-55rx
  2020/5xxx/CVE-2020-5273.json
Labels: accepted

#3617 Add CVE-2020-5294 for GHSA-774w-fg8p-7c8w
  2020/5xxx/CVE-2020-5294.json
Labels: accepted

#3621 Reject CVE-2019-11285
  2019/11xxx/CVE-2019-11285.json
Labels: accepted

#3622 byobu
  2019/7xxx/CVE-2019-7306.json
Labels: accepted

#3624 Ibm20200417 92346
  2019/4xxx/CVE-2019-4446.json
  2019/4xxx/CVE-2019-4644.json
  2019/4xxx/CVE-2019-4749.json
  2020/4xxx/CVE-2020-4277.json
Labels: accepted

#3625 Add CVE-2020-1751.
  2020/1xxx/CVE-2020-1751.json
Labels: accepted

#3627 JPCERT/CC CVE-2020-5569
  2020/5xxx/CVE-2020-5569.json
Labels: accepted

#3630 add CVE-2020-5265 for GHSA-7fmr-5vcc-329j
  2020/5xxx/CVE-2020-5265.json
Labels: accepted

#3629 add CVE-2020-5264 for GHSA-48vj-vvr6-jj4f
  2020/5xxx/CVE-2020-5264.json
Labels: accepted

#3632 add CVE-2020-5270 for GHSA-375w-q56h-h7qc
  2020/5xxx/CVE-2020-5270.json
Labels: accepted

#3631 add CVE-2020-5269 for GHSA-87jh-7xpg-6v93
  2020/5xxx/CVE-2020-5269.json
Labels: accepted

#3638 add CVE-2020-5285 for GHSA-j3r6-33hf-m8wh
  2020/5xxx/CVE-2020-5285.json
Labels: accepted

#3637 add CVE-2020-5279 for GHSA-74vp-ww64-w2gm
  2020/5xxx/CVE-2020-5279.json
Labels: accepted

#3636 add CVE-2020-5278 for GHSA-mrpj-67mq-3fr5
  2020/5xxx/CVE-2020-5278.json
Labels: accepted

#3635 add CVE-2020-5276 for GHSA-q6pr-42v5-v97q
  2020/5xxx/CVE-2020-5276.json
Labels: accepted

#3634 add CVE-2020-5272 for GHSA-rpg3-f23r-jmqv
  2020/5xxx/CVE-2020-5272.json
Labels: accepted

#3633 add CVE-2020-5271 for GHSA-m2x6-c2c6-pjrx
  2020/5xxx/CVE-2020-5271.json
Labels: accepted

#3642 add CVE-2020-5293 for GHSA-cvjj-grfv-f56w
  2020/5xxx/CVE-2020-5293.json
Labels: accepted

#3641 add CVE-2020-5288 for GHSA-4wxg-33h3-3w5r
  2020/5xxx/CVE-2020-5288.json
Labels: accepted

#3640 add CVE-2020-5287 for GHSA-r6rp-6gv6-r9hq
  2020/5xxx/CVE-2020-5287.json
Labels: accepted

#3639 add CVE-2020-5286 for GHSA-98j8-hvjv-x47j
  2020/5xxx/CVE-2020-5286.json
Labels: accepted

#3644 Add CVE-2020-11010 for GHSA-9j2c-x8qm-qmjq
  2020/11xxx/CVE-2020-11010.json
Labels: accepted

#3646 Adding data for CVE-2020-8099
  2020/8xxx/CVE-2020-8099.json
Labels: accepted

#3649 Update details for CVE-2020-1967 (OpenSSL)
  2020/1xxx/CVE-2020-1967.json
Labels: accepted

#3651 add CVE-2020-5268 for GHSA-9475-xg6m-j7pw
  2020/5xxx/CVE-2020-5268.json
Labels: accepted

#3647 CVE-2020-8895 for Google Earth
  2020/8xxx/CVE-2020-8895.json
Labels: accepted

#3653 add CVE-2020-11008 for GHSA-hjc9-x69f-jqj7
  2020/11xxx/CVE-2020-11008.json
Labels: accepted

#3654 add CVE-2020-5301 for GHSA-24m3-w8g9-jwpq
  2020/5xxx/CVE-2020-5301.json
Labels: accepted

#3655 Registering CVE-2019-20102 for an XSS in Confluence Server.
  2019/20xxx/CVE-2019-20102.json
Labels: accepted

#3657 Add CVE-2020-11011 for GHSA-4j97-6w6q-gxjx
  2020/11xxx/CVE-2020-11011.json
Labels: accepted

#3660 Update CVE-2020-1983
  2020/1xxx/CVE-2020-1983.json
Labels: accepted

#3661 ZDI assigns the following CVEs:
  2020/10xxx/CVE-2020-10889.json
  2020/10xxx/CVE-2020-10890.json
  2020/10xxx/CVE-2020-10891.json
  2020/10xxx/CVE-2020-10892.json
  2020/10xxx/CVE-2020-10893.json
  2020/10xxx/CVE-2020-10894.json
  2020/10xxx/CVE-2020-10895.json
  2020/10xxx/CVE-2020-10896.json
  2020/10xxx/CVE-2020-10897.json
  2020/10xxx/CVE-2020-10898.json
  2020/10xxx/CVE-2020-10899.json
  2020/10xxx/CVE-2020-10900.json
  2020/10xxx/CVE-2020-10901.json
  2020/10xxx/CVE-2020-10902.json
  2020/10xxx/CVE-2020-10903.json
  2020/10xxx/CVE-2020-10904.json
  2020/10xxx/CVE-2020-10905.json
  2020/10xxx/CVE-2020-10906.json
  2020/10xxx/CVE-2020-10907.json
  2020/10xxx/CVE-2020-10908.json
  2020/10xxx/CVE-2020-10909.json
  2020/10xxx/CVE-2020-10910.json
  2020/10xxx/CVE-2020-10911.json
  2020/10xxx/CVE-2020-10912.json
  2020/10xxx/CVE-2020-10913.json
  2020/10xxx/CVE-2020-10914.json
  2020/10xxx/CVE-2020-10915.json
  2020/8xxx/CVE-2020-8867.json
Labels: accepted

#3662 Apport vulns
  2020/8xxx/CVE-2020-8831.json
  2020/8xxx/CVE-2020-8833.json
Labels: accepted

#3663 Add CVE-2020-7350
  2020/7xxx/CVE-2020-7350.json
Labels: accepted

#3665 JPCERT/CC CVE-2020-5571
  2020/5xxx/CVE-2020-5571.json
Labels: accepted

#3668 Adding information for CVE-2019-17101
  2019/17xxx/CVE-2019-17101.json
Labels: accepted

#3669 add CVE-2020-11012 for GHSA-xv4r-vccv-mg4w
  2020/11xxx/CVE-2020-11012.json
Labels: accepted

#3670 Canonical CNAs: Ubuntu shiftfs cves
  2019/15xxx/CVE-2019-15791.json
  2019/15xxx/CVE-2019-15792.json
  2019/15xxx/CVE-2019-15793.json
  2019/15xxx/CVE-2019-15794.json
Labels: accepted

#3671 Ibm20200424 11488
  2019/4xxx/CVE-2019-4750.json
  2019/4xxx/CVE-2019-4751.json
  2020/4xxx/CVE-2020-4267.json
Labels: accepted

#3673 add CVE-2020-11013 for GHSA-q8q8-93cv-v6h8
  2020/11xxx/CVE-2020-11013.json
Labels: accepted

#3674 add CVE-2020-11004 for GHSA-qh57-rcff-gx54
  2020/11xxx/CVE-2020-11004.json
Labels: accepted

#3679 Ibm20200427 92422
  2019/4xxx/CVE-2019-4729.json
Labels: accepted

#3576 Added CVE-2020-1762
  2020/1xxx/CVE-2020-1762.json
Labels: needs work

#3680 CVE-2019-15790 in Apport
  2019/15xxx/CVE-2019-15790.json
Labels: accepted

#3681 JPCERT/CC batch
  2020/5xxx/CVE-2020-5562.json
  2020/5xxx/CVE-2020-5563.json
  2020/5xxx/CVE-2020-5564.json
  2020/5xxx/CVE-2020-5565.json
  2020/5xxx/CVE-2020-5566.json
  2020/5xxx/CVE-2020-5567.json
  2020/5xxx/CVE-2020-5568.json
Labels: accepted

#3682 JPCERT/CC CVE-2020-5570
  2020/5xxx/CVE-2020-5570.json
Labels: accepted

#3684 Ibm20200428 92427
  2020/4xxx/CVE-2020-4329.json
Labels: accepted

#3685 add CVE-2020-11014 for GHSA-cchm-grx2-g873
  2020/11xxx/CVE-2020-11014.json
Labels: accepted

#3688 Ibm20200429 9448
  2019/4xxx/CVE-2019-4286.json
  2019/4xxx/CVE-2019-4288.json
Labels: accepted

#3690 add CVE-2020-11009 for GHSA-5679-7qrc-5m7j
  2020/11xxx/CVE-2020-11009.json
Labels: accepted

#3691 add CVE-2020-11020 for GHSA-qpg4-4w7w-2mq5
  2020/11xxx/CVE-2020-11020.json
Labels: accepted

#3692 add CVE-2020-11021 for GHSA-9w6v-m7wp-jwg4
  2020/11xxx/CVE-2020-11021.json
Labels: accepted

#3693 Adding Cisco CVE-2019-16011
  2019/16xxx/CVE-2019-16011.json
Labels: accepted

#3694 Add CVE-2020-11024 for GHSA-g298-gp8q-h6j3
  2020/11xxx/CVE-2020-11024.json
Labels: accepted

#3695 Add CVE-2020-11023 for GHSA-jpcq-cgw6-v4j6
  2020/11xxx/CVE-2020-11023.json
Labels: accepted
