Repository CVEProject/cvelist, pull requests merged in 2020-07, with the labels that each got.

#4210 Add CVE-2019-20408 CVE-2020-14164 CVE-2020-14165 CVE-2020-14166 CVE-2020-14167 CVE-2020-14168 CVE-2020-14169 CVE-2020-4022 CVE-2020-4024 CVE-2020-4025 CVE-2020-4027 CVE-2020-4029
  2019/20xxx/CVE-2019-20408.json
  2020/14xxx/CVE-2020-14164.json
  2020/14xxx/CVE-2020-14165.json
  2020/14xxx/CVE-2020-14166.json
  2020/14xxx/CVE-2020-14167.json
  2020/14xxx/CVE-2020-14168.json
  2020/14xxx/CVE-2020-14169.json
  2020/4xxx/CVE-2020-4022.json
  2020/4xxx/CVE-2020-4024.json
  2020/4xxx/CVE-2020-4025.json
  2020/4xxx/CVE-2020-4027.json
  2020/4xxx/CVE-2020-4029.json
Labels: accepted

#4215 Ibm20200701 102131
  2019/4xxx/CVE-2019-4676.json
  2019/4xxx/CVE-2019-4704.json
  2019/4xxx/CVE-2019-4705.json
  2019/4xxx/CVE-2019-4706.json
  2020/4xxx/CVE-2020-4355.json
  2020/4xxx/CVE-2020-4363.json
  2020/4xxx/CVE-2020-4376.json
  2020/4xxx/CVE-2020-4386.json
  2020/4xxx/CVE-2020-4387.json
  2020/4xxx/CVE-2020-4414.json
  2020/4xxx/CVE-2020-4420.json
Labels: accepted

#4217 add CVE-2020-5238 for GHSA-7gc6-9qr5-hc85
  2020/5xxx/CVE-2020-5238.json
Labels: accepted

#4219 Register a Jira Server bug.
  2019/20xxx/CVE-2019-20417.json
Labels: accepted

#4224 Adding Cisco CVE-2020-3297
  2020/3xxx/CVE-2020-3297.json
Labels: accepted

#4223 Adding Cisco CVE-2020-3340
  2020/3xxx/CVE-2020-3340.json
Labels: accepted

#4222 Adding Cisco CVE-2020-3391
  2020/3xxx/CVE-2020-3391.json
Labels: accepted

#4221 Adding Cisco CVE-2020-3402
  2020/3xxx/CVE-2020-3402.json
Labels: accepted

#4228 Add CVEs for Jenkins 2020-07-02 security advisory
  2020/2xxx/CVE-2020-2201.json
  2020/2xxx/CVE-2020-2202.json
  2020/2xxx/CVE-2020-2203.json
  2020/2xxx/CVE-2020-2204.json
  2020/2xxx/CVE-2020-2205.json
  2020/2xxx/CVE-2020-2206.json
  2020/2xxx/CVE-2020-2207.json
  2020/2xxx/CVE-2020-2208.json
  2020/2xxx/CVE-2020-2209.json
  2020/2xxx/CVE-2020-2210.json
  2020/2xxx/CVE-2020-2211.json
  2020/2xxx/CVE-2020-2212.json
  2020/2xxx/CVE-2020-2213.json
  2020/2xxx/CVE-2020-2214.json
  2020/2xxx/CVE-2020-2215.json
  2020/2xxx/CVE-2020-2216.json
  2020/2xxx/CVE-2020-2217.json
  2020/2xxx/CVE-2020-2218.json
  2020/2xxx/CVE-2020-2219.json
Labels: accepted

#4232 add CVE-2020-15081 for GHSA-997j-f42g-x57c
  2020/15xxx/CVE-2020-15081.json
Labels: accepted

#4231 add CVE-2020-15080 for GHSA-492w-2pp5-xhvg
  2020/15xxx/CVE-2020-15080.json
Labels: accepted

#4229 add CVE-2020-11074 for GHSA-v4pg-q2cv-f7x4
  2020/11xxx/CVE-2020-11074.json
Labels: accepted

#4234 add CVE-2020-15083 for GHSA-qgh4-95j7-p3vj
  2020/15xxx/CVE-2020-15083.json
Labels: accepted

#4233 add CVE-2020-15082 for GHSA-mc98-xjm3-c4fm
  2020/15xxx/CVE-2020-15082.json
Labels: accepted

#4235 add CVE-2020-4061 for GHSA-3pc2-fm7p-q2vg
  2020/4xxx/CVE-2020-4061.json
Labels: accepted

#4237 add CVE-2020-15091 for GHSA-6jqj-f58p-mrw3
  2020/15xxx/CVE-2020-15091.json
Labels: accepted

#4236 add CVE-2020-4074 for GHSA-ccvh-jh5x-mpg4
  2020/4xxx/CVE-2020-4074.json
Labels: accepted

#4239 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20418.json
Labels: accepted

#4240 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20419.json
Labels: accepted

#4241 Registering a Jira Server issue.
  2020/14xxx/CVE-2020-14172.json
Labels: accepted

#4242 Registering a Jira Server issue.
  2020/14xxx/CVE-2020-14173.json
Labels: accepted

#4244 Publish CVE-2020-7282
  2020/7xxx/CVE-2020-7282.json
Labels: accepted

#4243 Publish CVE-2020-7821
  2020/7xxx/CVE-2020-7281.json
Labels: accepted

#4245 Publish CVE-2020-7283
  2020/7xxx/CVE-2020-7283.json
Labels: accepted

#4247 Assign CVE-2020-10281
  2020/10xxx/CVE-2020-10281.json
Labels: accepted

#4246 Assign CVE-2020-10282
  2020/10xxx/CVE-2020-10282.json
Labels: accepted

#4248 Update CVE-2020-7284.json
  2020/7xxx/CVE-2020-7284.json
Labels: accepted

#4251 Added CVE-2020-5352,5356,5368,5371,5372
  2020/5xxx/CVE-2020-5352.json
  2020/5xxx/CVE-2020-5356.json
  2020/5xxx/CVE-2020-5368.json
  2020/5xxx/CVE-2020-5371.json
  2020/5xxx/CVE-2020-5372.json
Labels: accepted

#4254 add CVE-2020-4077 for GHSA-h9jc-284h-533g
  2020/4xxx/CVE-2020-4077.json
Labels: accepted

#4253 add CVE-2020-4076 for GHSA-m93v-9qjc-3g79
  2020/4xxx/CVE-2020-4076.json
Labels: accepted

#4252 add CVE-2020-4075 for GHSA-f9mq-jph6-9mhm
  2020/4xxx/CVE-2020-4075.json
Labels: accepted

#4255 add CVE-2020-15096 for GHSA-6vrv-94jv-crrg
  2020/15xxx/CVE-2020-15096.json
Labels: accepted

#4256 JPCERT/CC batch
  2020/5xxx/CVE-2020-5595.json
  2020/5xxx/CVE-2020-5596.json
  2020/5xxx/CVE-2020-5597.json
  2020/5xxx/CVE-2020-5598.json
  2020/5xxx/CVE-2020-5599.json
  2020/5xxx/CVE-2020-5600.json
Labels: accepted

#4264 Add CVE-2020-15095 for GHSA-93f3-23rq-pjfp
  2020/15xxx/CVE-2020-15095.json
Labels: accepted

#4265 initial add of CVE-2020-8519 CVE-2020-8520 CVE-2020-8521
  2020/8xxx/CVE-2020-8519.json
  2020/8xxx/CVE-2020-8520.json
  2020/8xxx/CVE-2020-8521.json
Labels: accepted

#4267 CVE-2020-8916 - Openthread/wpantund
  2020/8xxx/CVE-2020-8916.json
Labels: accepted

#4268 Add TWCERT/CC CVE-2020-3931
  2020/3xxx/CVE-2020-3931.json
Labels: accepted

#4269 CVEs assigned in Palo Alto Networks Security Advisories for July 2020
  2020/1xxx/CVE-2020-1982.json
  2020/2xxx/CVE-2020-2030.json
  2020/2xxx/CVE-2020-2031.json
  2020/2xxx/CVE-2020-2034.json
Labels: accepted

#4272 CVE-2020-5974.json
  2020/5xxx/CVE-2020-5974.json
Labels: accepted

#4273 JPCERT/CC CVE-2020-5604
  2020/5xxx/CVE-2020-5604.json
Labels: accepted

#4277 Added CVE-2020-5366
  2020/5xxx/CVE-2020-5366.json
Labels: accepted

#4270 CVE-2019-17638
  2019/17xxx/CVE-2019-17638.json
Labels: accepted

#4279 add CVE-2020-15092 for GHSA-2jpm-827p-j44g
  2020/15xxx/CVE-2020-15092.json
Labels: accepted

#4280 add CVE-2020-15093 for GHSA-5q2r-92f9-4m49
  2020/15xxx/CVE-2020-15093.json
Labels: accepted

#4281 Ibm20200709 145946
  2020/4xxx/CVE-2020-4173.json
  2020/4xxx/CVE-2020-4305.json
Labels: accepted

#4282 JPCERT/CC CVE-2020-5607
  2020/5xxx/CVE-2020-5607.json
Labels: accepted

#4283 add CVE-2020-11081 for GHSA-2xwp-8fv7-c5pm
  2020/11xxx/CVE-2020-11081.json
Labels: accepted

#4284 add CVE-2020-11061 for GHSA-mm45-cg35-54j4
  2020/11xxx/CVE-2020-11061.json
Labels: accepted

#4285 add CVE-2020-4042 for GHSA-vqpj-2vhj-h752
  2020/4xxx/CVE-2020-4042.json
Labels: accepted

#4287 add CVE-2020-15105 for GHSA-vhr6-pvjm-9qwf
  2020/15xxx/CVE-2020-15105.json
Labels: accepted

#4288 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20897.json
Labels: accepted

#4289 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20898.json
Labels: accepted

#4290 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20899.json
Labels: accepted

#4291 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20900.json
Labels: accepted

#4293 Registering a Jira Server issue.
  2020/14xxx/CVE-2020-14174.json
Labels: accepted

#4294 Registering a Jira Server issue.
  2019/20xxx/CVE-2019-20901.json
Labels: accepted

#4295 Ibm20200713 1071
  2019/4xxx/CVE-2019-4591.json
Labels: accepted

#3122 CVE-2019-19338 update
  2019/19xxx/CVE-2019-19338.json
Labels: needs work

#4297 Ibm20200714 9533
  2020/4xxx/CVE-2020-4364.json
  2020/4xxx/CVE-2020-4510.json
  2020/4xxx/CVE-2020-4511.json
  2020/4xxx/CVE-2020-4512.json
  2020/4xxx/CVE-2020-4513.json
Labels: accepted

#4298 Add CVE-2020-15100 for GHSA-9cfv-9463-8gqv
  2020/15xxx/CVE-2020-15100.json
Labels: accepted

#4299 Added CVE-2020-5373,5374
  2020/5xxx/CVE-2020-5373.json
  2020/5xxx/CVE-2020-5374.json
Labels: accepted

#4300 add CVE-2020-5246 for GHSA-v955-7g22-2p49
  2020/5xxx/CVE-2020-5246.json
Labels: accepted

#4302 add CVE-2020-11083 for GHSA-w4pj-7p68-3vgv
  2020/11xxx/CVE-2020-11083.json
Labels: accepted

#4304 add CVE-2020-11084 for GHSA-4xvp-35fx-hjjj
  2020/11xxx/CVE-2020-11084.json
Labels: accepted

#4305 add CVE-2020-15101 for GHSA-7pmh-vrww-25xx
  2020/15xxx/CVE-2020-15101.json
Labels: accepted

#4306 add CVE-2020-15104 for GHSA-w5f5-6qhq-hhrg
  2020/15xxx/CVE-2020-15104.json
Labels: accepted

#4310 Update CVE-2020-7292.json
  2020/7xxx/CVE-2020-7292.json
Labels: accepted

#4311 CVE-2019-17637
  2019/17xxx/CVE-2019-17637.json
Labels: accepted

#4314 Add CVEs for Jenkins 2020-07-15 security advisory
  2020/2xxx/CVE-2020-2220.json
  2020/2xxx/CVE-2020-2221.json
  2020/2xxx/CVE-2020-2222.json
  2020/2xxx/CVE-2020-2223.json
  2020/2xxx/CVE-2020-2224.json
  2020/2xxx/CVE-2020-2225.json
  2020/2xxx/CVE-2020-2226.json
  2020/2xxx/CVE-2020-2227.json
  2020/2xxx/CVE-2020-2228.json
Labels: accepted

#4315 Add CVE-2020-15117 for GHSA-chfm-333q-gfpp
  2020/15xxx/CVE-2020-15117.json
Labels: accepted

#4316 CVE-2020-15602 and CVE-2020-15603
  2020/15xxx/CVE-2020-15602.json
  2020/15xxx/CVE-2020-15603.json
Labels: accepted

#4317 Cve 2020 10284
  2020/10xxx/CVE-2020-10284.json
Labels: accepted

#4318 Cve 2020 10285
  2020/10xxx/CVE-2020-10285.json
Labels: accepted

#4319 Cve 2020 10286
  2020/10xxx/CVE-2020-10286.json
Labels: accepted

#4312 CVE-2019-17639
  2019/17xxx/CVE-2019-17639.json
Labels: accepted

#4313 Add CVE-2020-15107 for GHSA-7wjx-wcwg-w999
  2020/15xxx/CVE-2020-15107.json
Labels: accepted

#4321 Assign CVE-2020-10288
  2020/10xxx/CVE-2020-10288.json
Labels: accepted

#4320 Assign CVE-2020-10287
  2020/10xxx/CVE-2020-10287.json
Labels: accepted

#4323 Ibm20200716 11342
  2019/4xxx/CVE-2019-4747.json
  2019/4xxx/CVE-2019-4748.json
  2020/4xxx/CVE-2020-4316.json
  2020/4xxx/CVE-2020-4462.json
Labels: accepted

#4324 Adding Cisco CVE-2020-3140
  2020/3xxx/CVE-2020-3140.json
Labels: accepted

#4356 Adding Cisco CVE-2020-3144
  2020/3xxx/CVE-2020-3144.json
Labels: accepted

#4355 Adding Cisco CVE-2020-3145
  2020/3xxx/CVE-2020-3145.json
Labels: accepted

#4354 Adding Cisco CVE-2020-3146
  2020/3xxx/CVE-2020-3146.json
Labels: accepted

#4353 Adding Cisco CVE-2020-3150
  2020/3xxx/CVE-2020-3150.json
Labels: accepted

#4352 Adding Cisco CVE-2020-3180
  2020/3xxx/CVE-2020-3180.json
Labels: accepted

#4351 Adding Cisco CVE-2020-3197
  2020/3xxx/CVE-2020-3197.json
Labels: accepted

#4350 Adding Cisco CVE-2020-3323
  2020/3xxx/CVE-2020-3323.json
Labels: accepted

#4349 Adding Cisco CVE-2020-3330
  2020/3xxx/CVE-2020-3330.json
Labels: accepted

#4348 Adding Cisco CVE-2020-3331
  2020/3xxx/CVE-2020-3331.json
Labels: accepted

#4347 Adding Cisco CVE-2020-3332
  2020/3xxx/CVE-2020-3332.json
Labels: accepted

#4346 Adding Cisco CVE-2020-3345
  2020/3xxx/CVE-2020-3345.json
Labels: accepted

#4345 Adding Cisco CVE-2020-3348
  2020/3xxx/CVE-2020-3348.json
Labels: accepted

#4344 Adding Cisco CVE-2020-3349
  2020/3xxx/CVE-2020-3349.json
Labels: accepted

#4343 Adding Cisco CVE-2020-3351
  2020/3xxx/CVE-2020-3351.json
Labels: accepted

#4342 Adding Cisco CVE-2020-3357
  2020/3xxx/CVE-2020-3357.json
Labels: accepted

#4341 Adding Cisco CVE-2020-3358
  2020/3xxx/CVE-2020-3358.json
Labels: accepted

#4340 Adding Cisco CVE-2020-3369
  2020/3xxx/CVE-2020-3369.json
Labels: accepted

#4339 Adding Cisco CVE-2020-3370
  2020/3xxx/CVE-2020-3370.json
Labels: accepted

#4338 Adding Cisco CVE-2020-3372
  2020/3xxx/CVE-2020-3372.json
Labels: accepted

#4337 Adding Cisco CVE-2020-3378
  2020/3xxx/CVE-2020-3378.json
Labels: accepted

#4336 Adding Cisco CVE-2020-3379
  2020/3xxx/CVE-2020-3379.json
Labels: accepted

#4335 Adding Cisco CVE-2020-3380
  2020/3xxx/CVE-2020-3380.json
Labels: accepted

#4334 Adding Cisco CVE-2020-3381
  2020/3xxx/CVE-2020-3381.json
Labels: accepted

#4333 Adding Cisco CVE-2020-3385
  2020/3xxx/CVE-2020-3385.json
Labels: accepted

#4332 Adding Cisco CVE-2020-3387
  2020/3xxx/CVE-2020-3387.json
Labels: accepted

#4331 Adding Cisco CVE-2020-3388
  2020/3xxx/CVE-2020-3388.json
Labels: accepted

#4329 Adding Cisco CVE-2020-3405
  2020/3xxx/CVE-2020-3405.json
Labels: accepted

#4330 Adding Cisco CVE-2020-3401
  2020/3xxx/CVE-2020-3401.json
Labels: accepted

#4328 Adding Cisco CVE-2020-3406
  2020/3xxx/CVE-2020-3406.json
Labels: accepted

#4327 Adding Cisco CVE-2020-3437
  2020/3xxx/CVE-2020-3437.json
Labels: accepted

#4325 Adding Cisco CVE-2020-3468
  2020/3xxx/CVE-2020-3468.json
Labels: accepted

#4326 Adding Cisco CVE-2020-3450
  2020/3xxx/CVE-2020-3450.json
Labels: accepted

#4360 Ibm20200717 9428
  2020/4xxx/CVE-2020-4464.json
Labels: accepted

#4361 CVE-2020-5130 and CVE-2020-5131
  2020/5xxx/CVE-2020-5130.json
  2020/5xxx/CVE-2020-5131.json
Labels: accepted

#4362 juniper 2020-07-08
  2020/1xxx/CVE-2020-1640.json
  2020/1xxx/CVE-2020-1641.json
  2020/1xxx/CVE-2020-1643.json
  2020/1xxx/CVE-2020-1644.json
  2020/1xxx/CVE-2020-1645.json
  2020/1xxx/CVE-2020-1646.json
  2020/1xxx/CVE-2020-1647.json
  2020/1xxx/CVE-2020-1648.json
  2020/1xxx/CVE-2020-1649.json
  2020/1xxx/CVE-2020-1650.json
  2020/1xxx/CVE-2020-1651.json
  2020/1xxx/CVE-2020-1652.json
  2020/1xxx/CVE-2020-1653.json
  2020/1xxx/CVE-2020-1654.json
  2020/1xxx/CVE-2020-1655.json
Labels: accepted

#4363 Add CVE-2020-15108 for GHSA-qv6w-68gq-wx2v
  2020/15xxx/CVE-2020-15108.json
Labels: accepted

#4364 Add CVE-2020-15110 for GHSA-v7m9-9497-p9gr
  2020/15xxx/CVE-2020-15110.json
Labels: accepted

#4366 Ibm20200720 10039
  2020/4xxx/CVE-2020-4361.json
  2020/4xxx/CVE-2020-4466.json
  2020/4xxx/CVE-2020-4527.json
Labels: accepted

#4278 Update CVE-2020-10782.json
  2020/10xxx/CVE-2020-10782.json
Labels: needs work

#4367 add CVE-2020-15123 for GHSA-xp63-6vf5-xf3v
  2020/15xxx/CVE-2020-15123.json
Labels: accepted

#4369 add CVE-2020-15111 for GHSA-9cx9-x2gp-9qvh
  2020/15xxx/CVE-2020-15111.json
Labels: accepted

#4370 Adding ClamAV CVE-2020-3481
  2020/3xxx/CVE-2020-3481.json
Labels: accepted

#4371 add CVE-2020-15118 for GHSA-2473-9hgq-j7xw
  2020/15xxx/CVE-2020-15118.json
Labels: accepted

#4372 add CVE-2020-15121 for GHSA-r552-vp94-9358
  2020/15xxx/CVE-2020-15121.json
Labels: accepted

#4374 Adding Cisco DUO CVE-2020-3442
  2020/3xxx/CVE-2020-3442.json
Labels: accepted

#4373 OSA-2020-13
  2020/1xxx/CVE-2020-1776.json
Labels: accepted

#4375 Registering an accidentally-duplicated issue.
  2019/20xxx/CVE-2019-20417.json
Labels: accepted

#4376 Update CVE-2020-7263.json
  2020/7xxx/CVE-2020-7263.json
Labels: accepted

#4377 add cve-2020-12499
  2020/12xxx/CVE-2020-12499.json
Labels: missing version, needs work

#4286 add CVE-2020-15102 for GHSA-6292-4qpg-hvfg
  2020/15xxx/CVE-2020-15102.json
Labels: accepted

#4383 Add TWCERT/CC CVE-2020-12774
  2020/12xxx/CVE-2020-12774.json
Labels: accepted

#4378 Publish CVE-2020-8559
  2020/8xxx/CVE-2020-8559.json
Labels: accepted

#4385 Chrome 83 and 84 CVEs.
  2020/6xxx/CVE-2020-6505.json
  2020/6xxx/CVE-2020-6506.json
  2020/6xxx/CVE-2020-6507.json
  2020/6xxx/CVE-2020-6509.json
  2020/6xxx/CVE-2020-6510.json
  2020/6xxx/CVE-2020-6511.json
  2020/6xxx/CVE-2020-6512.json
  2020/6xxx/CVE-2020-6513.json
  2020/6xxx/CVE-2020-6514.json
  2020/6xxx/CVE-2020-6515.json
  2020/6xxx/CVE-2020-6516.json
  2020/6xxx/CVE-2020-6517.json
  2020/6xxx/CVE-2020-6518.json
  2020/6xxx/CVE-2020-6519.json
  2020/6xxx/CVE-2020-6520.json
  2020/6xxx/CVE-2020-6521.json
  2020/6xxx/CVE-2020-6522.json
  2020/6xxx/CVE-2020-6523.json
  2020/6xxx/CVE-2020-6524.json
  2020/6xxx/CVE-2020-6525.json
  2020/6xxx/CVE-2020-6526.json
  2020/6xxx/CVE-2020-6527.json
  2020/6xxx/CVE-2020-6528.json
  2020/6xxx/CVE-2020-6529.json
  2020/6xxx/CVE-2020-6530.json
  2020/6xxx/CVE-2020-6531.json
  2020/6xxx/CVE-2020-6533.json
  2020/6xxx/CVE-2020-6534.json
  2020/6xxx/CVE-2020-6535.json
  2020/6xxx/CVE-2020-6536.json
Labels: accepted

#4382 Updating the affected version ranges of this CVE ID.
  2020/14xxx/CVE-2020-14172.json
Labels: accepted

#4386 add CVE-2020-15124 for GHSA-7gwq-xqw3-cr63
  2020/15xxx/CVE-2020-15124.json
Labels: accepted

#4381 trust-store (Ubuntu) vulnerability
  2014/1xxx/CVE-2014-1422.json
Labels: accepted

#4387 Adding Cisco CVE-2020-3452
  2020/3xxx/CVE-2020-3452.json
Labels: accepted

#4388 Ibm20200722 162355
  2020/4xxx/CVE-2020-4369.json
  2020/4xxx/CVE-2020-4371.json
  2020/4xxx/CVE-2020-4372.json
  2020/4xxx/CVE-2020-4385.json
  2020/4xxx/CVE-2020-4397.json
  2020/4xxx/CVE-2020-4399.json
  2020/4xxx/CVE-2020-4400.json
Labels: accepted

#4389 ZDI assigns the following CVEs:
  2020/10xxx/CVE-2020-10917.json
Labels: accepted

#4390 add CVE-2020-15126 for GHSA-236h-rqv8-8q73
  2020/15xxx/CVE-2020-15126.json
Labels: accepted

#4391 Registering a URL reference for an issue in Jira Server.
  2012/6xxx/CVE-2012-6342.json
Labels: accepted

#4392 Publish CVE-2019-11252
  2019/11xxx/CVE-2019-11252.json
Labels: accepted

#4394 Correct affected versions for cve-2020-8559
  2020/8xxx/CVE-2020-8559.json
Labels: accepted

#4396 ZDI assigns the following CVEs:
  2020/10xxx/CVE-2020-10918.json
  2020/10xxx/CVE-2020-10919.json
  2020/10xxx/CVE-2020-10920.json
  2020/10xxx/CVE-2020-10921.json
  2020/10xxx/CVE-2020-10922.json
Labels: accepted

#4398 Ibm20200723 12219
  2020/4xxx/CVE-2020-4447.json
Labels: accepted

#4395 Publish details for CVE-2020-8557
  2020/8xxx/CVE-2020-8557.json
Labels: accepted

#4400 ZDI assigns the following CVEs:
  2020/15xxx/CVE-2020-15631.json
  2020/15xxx/CVE-2020-15632.json
  2020/15xxx/CVE-2020-15633.json
Labels: accepted

#4401 Registering a Confluence Server issue.
  2020/14xxx/CVE-2020-14175.json
Labels: accepted

#4402 CVE-2020-14307
  2020/14xxx/CVE-2020-14307.json
Labels: accepted

#4403 CVE-2020-14297
  2020/14xxx/CVE-2020-14297.json
Labels: accepted
